"""Replace cached wiki icons with original textures from installed game archives."""
import json
import io
import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse
import UnityPy

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from constants import ABILITY_DETAILS
from sigil_data import SIGIL_LIBRARY
from talent_data import TALENTS


def key(name):
    return re.sub('[^a-z0-9]', '', Path(name).stem.casefold())


def main():
    targets = {}
    def add(texture, path):
        targets.setdefault(key(texture), []).append(path)
    for path in (ROOT / 'web/assets/talent-icons').glob('*.png'):
        add(path.name, path)
    for entry in SIGIL_LIBRARY:
        add(entry['wiki_image'], ROOT / 'web' / entry['image_url'])
    talent_icons = {t['name']: unquote(urlparse(t.get('icon_url', '')).path).split('/revision')[0].split('/')[-1] for t in TALENTS}
    spell_starters = {'Заряженный кулак':'Spell-ShockTouch', 'Ледяная хватка':'Spell-FrostTouch',
                     'Касание титана':'Spell-StrengthTouch', 'Касание истощения':'Spell-WeakenTouch'}
    for name, ability in ABILITY_DETAILS.items():
        texture = talent_icons.get(name) or spell_starters.get(name)
        if texture:
            add(texture, ROOT / 'web' / ability['icon'])
    manifest = {}
    game = Path('C:/Games/Tyranny/Data')
    bundles = [game / 'bundles' / (name + '.unity3d') for name in
        ['abilities', 'afflictions', 'spells', 'characters', 'items', 'lists', 'progression_tables', 'dlc00', 'dlc01', 'dlc02', 'dlc03']]
    for archive in [game / 'resources.assets', *sorted(game.glob('sharedassets*.assets')), *bundles]:
        env = UnityPy.load(str(archive))
        for obj in env.objects:
            if obj.type.name != 'Texture2D':
                continue
            texture = obj.read()
            paths = targets.get(key(texture.m_Name), [])
            for path in paths:
                relative = path.relative_to(ROOT / 'web').as_posix()
                if relative in manifest:
                    continue
                image = texture.image
                buffer = io.BytesIO()
                image.save(buffer, format='WEBP' if path.suffix == '.webp' else 'PNG', **({'lossless': True} if path.suffix == '.webp' else {}))
                path.write_bytes(buffer.getvalue())
                manifest[relative] = {'archive': archive.name, 'texture': texture.m_Name,
                                      'width': image.width, 'height': image.height}
    expected = {p.relative_to(ROOT / 'web').as_posix() for paths in targets.values() for p in paths}
    payload = {'source':'Tyranny installed game archives', 'icons':manifest, 'unmatched':sorted(expected-set(manifest))}
    (ROOT / 'web/assets/game-icons.json').write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding='utf-8')
    # Prepared spells have their own coloured HUD symbols, unlike crafting cores.
    cores = {'Огонь':'fire','Холод':'frost','Молния':'shock','Жизнь':'heal','Истощение':'weaken',
             'Эмоции':'passion','Рвение':'strength','Сила':'gravity','Камень':'stone','Терратус':'gravelight','Иллюзия':'illusion'}
    shapes = {'Область влияния':['field'], 'Направленная сила':['trap','line','bolt'],
              'Хаотическое нисхождение':['rain'], 'Сосредоточенное намерение':['melee'],
              'Проводимая сила':['cone'], 'Охранная форма':['armor'],
              'Материальная сила':['weapon','wpn'], 'Ближнее действие':['aura'], 'Дальний удар':['bolt']}
    spell_icons = {}
    for core, prefix in cores.items():
        for expression, suffixes in shapes.items():
            candidates = [f'fx_spellicon_{prefix}_{suffix}.png' for suffix in suffixes] + [f'fx_spellicon_{prefix}.png']
            filename = next(name for name in candidates if (ROOT / 'web/assets/game-combat' / name).is_file())
            spell_icons[f'{core}|{expression}'] = 'assets/game-combat/' + filename
    (ROOT / 'web/game-spell-icons.js').write_text('/* Original game HUD textures; generated by extract_game_icons.py. */\nconst GAME_SPELL_ICONS = '+json.dumps(spell_icons, ensure_ascii=False, indent=2)+';\n', encoding='utf-8')
    print(f'Original game icons: {len(manifest)} / {len(expected)}')
    for path in payload['unmatched']:
        print('UNMATCHED', path)


if __name__ == '__main__':
    main()
