const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes={},node=k=>nodes[k]??={innerHTML:'',hidden:false,value:'',insertAdjacentHTML(_,s){this.innerHTML+=s}};
const shop={settings:{name:'Лавка',enabled:1},shops:[{key:'consumables',name:'Припасы'},{key:'weapons',name:'Оружие'},{key:'armor',name:'Броня'}],categories:['Луки'],qualities:['Обычное'],items:[{id:1,name:'Лук',category:'Луки',quality:'Обычное',value:100,buy_price:100,stock:4,image_url:'assets/test.png'}],saleOffers:[],wallet:{copper:50}};
const context=vm.createContext({document:{querySelector:node,addEventListener(){}},$:node,URLSearchParams,renderCabinet(){},renderTab(){},esc:v=>String(v??''),data:{inventory:[],wallet:{}},tab:'shop',token:'test',toast(){},request(){return shop},base(){return '/api/admin/test'}});
vm.runInContext(fs.readFileSync('web/player-shop.js','utf8'),context);
const rings=context.moneyIcons({iron:5,bronze:12,copper:90});
for(const [key,name,icon,count] of [['iron','Железные кольца','Iron',5],['bronze','Бронзовые кольца','Bronze',12],['copper','Медные кольца','Copper',90]]){
 assert(rings.includes(`data-ring="${key}" tabindex="0" aria-label="${name}: ${count}"`));
 assert(rings.includes(`Imperial${icon}Ring_S.png`));
 assert(fs.existsSync(`web/assets/item-icons/Imperial${icon}Ring_S.png`));
 assert(rings.includes(`aria-hidden="true">${name}</span>`));
}
assert.equal((context.moneyIcons().match(/<b>0<\/b>/g)||[]).length,3);
context.renderCabinet();
assert(node('#profile-head').innerHTML.includes('wallet-rings'));
assert(!node('#profile-head').innerHTML.includes('0 железных ·'));
vm.runInContext(`playerShop=${JSON.stringify(shop)};renderPlayerShop()`,context);
assert(node('#panel').innerHTML.includes('data-player-merchant="weapons"'));
assert(node('#panel').innerHTML.includes('player-shop-category'));
assert(!node('#panel').innerHTML.includes('Лавка украшений'));
assert(node('#panel').innerHTML.includes('Обычное'));
vm.runInContext("playerShopKey='weapons';playerShopCategory='Луки'",context);
assert(vm.runInContext('playerShopURL()',context).includes('shopKey=weapons'));
context.campaignWorkspace=s=>node('#editor').innerHTML=s;
context.openMasterShop=()=>{};context.renderMasterShop=()=>{};context.editMasterShop=()=>{};
vm.runInContext(fs.readFileSync('web/admin-catalog.js','utf8'),context);
vm.runInContext(`masterCatalog=${JSON.stringify({items:shop.items,total:101,categories:['Луки','Аксессуары'],qualities:['Обычное'],filters:{q:'',category:'',quality:'',sort:'name',minPrice:'0',maxPrice:'1000'}})};renderItemCatalog()`,context);
assert(node('#editor').innerHTML.includes('Аксессуары'));
assert(node('#editor').innerHTML.includes('data-catalog-page="50"'));
assert(node('#editor').innerHTML.includes('data-catalog-detail="1"'));
assert(node('#editor').innerHTML.includes('maxPrice'));
console.log('Shop UI: store tabs, category/quality filters, catalogue pagination and detail selection OK');
