const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context=vm.createContext({renderTraining(){},playCombatEffect(){},trainingMutate(){},esc:v=>String(v??'').replaceAll('<','&lt;'),roundText:n=>`${n} раундов`});
vm.runInContext(fs.readFileSync('web/combat-feedback.js','utf8'),context);
const before={width:10,height:10,tokens:[{id:'p',name:'Персонаж',x:1,y:1,health:50},{id:'e',name:'Цель',x:2,y:2,health:20}]};
const after={width:10,height:10,tokens:[{id:'p',name:'Персонаж',x:1,y:1,health:60}]};
context.before=before;context.after=after;
const changes=JSON.parse(JSON.stringify(vm.runInContext('combatHealthChanges(before,after)',context)));
assert.deepEqual(changes.map(x=>[x.id,x.delta]),[['p',10],['e',-20]]);
assert.equal(vm.runInContext('combatHealthChanges(before,before).length',context),0);
assert.equal(vm.runInContext('combatHealthChanges(null,after).length',context),0);
assert.equal(vm.runInContext('combatStatusDuration({until:3},2)',context),'2 раундов');
assert.equal(vm.runInContext('combatStatusDuration({until:999999},2)',context),'до конца боя');
assert.equal(vm.runInContext('combatStatusLabel({name:"Сила: +2 на 6 раундов",until:6},3)',context),'Сила: +2 · 4 раундов');
assert.equal(vm.runInContext('combatStatusLabel({name:"Отравление",until:3,stacks:2},3)',context),'Отравление ×2 · 1 раундов');
context.state={round:2,dummy:{name:'<Цель>',health:20,healthMax:100,armor:3},turn:{distanceToTarget:4,cover:'нет'},grid:{selectedTargetId:'e',tokens:[]},conditions:{e:{root:{name:'Скован',until:3}}}};
const card=vm.runInContext('combatTargetCard(state)',context);
assert(card.includes('&lt;Цель>'));assert(card.includes('20/100'));assert(card.includes('Броня 3'));assert(card.includes('4 м'));assert(card.includes('aria-valuenow="20"'));
const page=fs.readFileSync('web/archive.html','utf8'),css=fs.readFileSync('web/combat-polish.css','utf8');
assert(page.indexOf('combat-feedback.js')>page.indexOf('combat-ui.js'),'Feedback extends the initialized combat UI');
assert(page.indexOf('combat-polish.css')>page.indexOf('combat-layout.css'));
assert(css.includes('.combat-aim-overlay{position:sticky'),'Aim hint stays outside the scrolling coordinate grid');
assert(css.includes('.combat-floating-result.healing'),'Healing uses its own visual result color');
assert(!css.includes('animation:combat-result-rise'),'Health result is animated only once');
console.log('Combat feedback: actual health deltas, fallen targets, remaining status rounds, target card and escaping OK');
