const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes={},node=k=>nodes[k]??={innerHTML:'',hidden:false,insertAdjacentHTML(){},focus(){},setSelectionRange(){}};
const events={},messages=[],requests=[];
let respond;
const escape=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const ctx=vm.createContext({document:{querySelector:node,addEventListener:(kind,fn)=>events[kind]=fn},$:node,renderCabinet(){},renderTab(){},esc:escape,data:{character:{background:'Скованный Ремеслом'},inventory:[]},tab:'crafting',moneyText(){return 'Кольца'},itemVisual:i=>`<img data-quality="${escape(i.quality)}">`,normalize:v=>v,request:(url,options)=>{requests.push({url,options});return options?new Promise(resolve=>respond=resolve):Promise.resolve(ctx.data)},toast:m=>messages.push(m),token:'test'});
vm.runInContext(fs.readFileSync('web/player-crafting.js','utf8'),ctx);
const item={name:'Меч',quality:'Выдающееся',damage_min:20,damage_max:30,recovery:.05,category:'Одноручное оружие',properties:{'Точность':'+8','Броня по типу урона':'Рубящий: 8; Колющий: 4',gameData:{secret:'RAW_EXPORT'}},value:100};
const data={wallet:{totalCopper:1000},jobs:[],scrolls:[],upgrades:[{inventoryId:1,item,result:{...item,quality:'Безупречное',damage_min:25,properties:{'Точность':'+10'}},ingredients:[],recipe:{cost:50,hours:5}}],recipes:[{key:'test',name:'Зелье',outputItem:{...item,name:'Зелье'},known:false,ingredients:[],cost:350,hours:1}]};
vm.runInContext(`craftingData=${JSON.stringify(data)};craftingSelection='1';renderCrafting()`,ctx);
assert(node('#panel').innerHTML.includes('ПОСЛЕ УЛУЧШЕНИЯ'));
assert(node('#panel').innerHTML.includes('Безупречное'));
assert(node('#panel').innerHTML.includes('data-craft-action="upgrade"'));
assert(node('#panel').innerHTML.includes('data-craft-back'));
assert(node('#panel').innerHTML.includes('В ДАННЫЙ МОМЕНТ:'));
assert(node('#panel').innerHTML.includes('20–30'));
assert(node('#panel').innerHTML.includes('25–30'));
assert(node('#panel').innerHTML.includes('+8'));
assert(node('#panel').innerHTML.includes('+10'));
assert(node('#panel').innerHTML.includes('Рубящий: 8; Колющий: 4'));
assert(node('#panel').innerHTML.includes('0,05 раундов'));
assert(!node('#panel').innerHTML.includes('RAW_EXPORT'));
assert(!node('#panel').innerHTML.includes('Цена предмета'));
assert(!node('#panel').innerHTML.includes('data-craft-select'));
assert(node('#panel').innerHTML.includes('Улучшение мгновенно'));
assert(!node('#panel').innerHTML.includes('5 ч'));
assert(!node('#panel').innerHTML.includes('работники'));
const click=dataset=>({target:{closest:selector=>selector==='[data-craft-action]'?{dataset,disabled:false}:null}});
events.click({target:{closest:selector=>selector==='[data-craft-back]'?{}:null}});
assert.equal(vm.runInContext('craftingSelection',ctx),null);
assert(node('#panel').innerHTML.includes('data-craft-select="1"'));
vm.runInContext("craftingKind='consumable';craftingSelection='test';renderCrafting()",ctx);
assert(node('#panel').innerHTML.includes('приобретите и изучите рецепт'));
assert(!node('#panel').innerHTML.includes('data-craft-action="craft"'));
vm.runInContext("craftingKind='upgrade';craftingSelection='1';craftingData.wallet={totalCopper:49};renderCrafting()",ctx);
assert(node('#panel').innerHTML.includes('Недостаточно колец'));
assert.match(node('#panel').innerHTML,/data-craft-action="upgrade"[^>]+disabled/);
vm.runInContext("craftingData.wallet={iron:0,bronze:1,copper:0}",ctx);
assert.equal(vm.runInContext('craftBalance()',ctx),100);
const material={id:7,name:'Кожа',image_url:'skin.png'};
const ingredient={item:material,quantity:2,consumed:true};
ctx.data.inventory=[{id:7,quantity:99,equipped_slot:'Торс'},{id:7,quantity:1,equipped_slot:null}];
vm.runInContext(`craftingData.upgrades[0].ingredients=${JSON.stringify([ingredient])};renderCrafting()`,ctx);
assert(node('#panel').innerHTML.includes('Недостаточно материала: Кожа'));
assert(node('#panel').innerHTML.includes('1 / 2'));
ctx.data.inventory[1].quantity=2;
vm.runInContext('renderCrafting()',ctx);
assert.doesNotMatch(node('#panel').innerHTML,/data-craft-action="upgrade"[^>]+disabled/);
assert.equal(vm.runInContext('craftQuantity(1.5)',ctx),null);
assert.equal(vm.runInContext('craftQuantity(0)',ctx),null);
assert.equal(vm.runInContext('craftQuantity(16)',ctx),null);
assert.equal(vm.runInContext('craftQuantity(15)',ctx),15);
vm.runInContext("craftingKind='consumable';craftingSelection='test';craftingData.recipes[0].known=true;renderCrafting()",ctx);
assert(node('#panel').innerHTML.includes('data-craft-action="craft"'));
node('[data-craft-action="craft"]').disabled=false;
events.input({target:{id:'craft-quantity',value:'1.5'}});
assert(node('[data-craft-action="craft"]').disabled);
assert(node('#craft-blocked').textContent.includes('целым числом'));
events.input({target:{id:'craft-quantity',value:'1'}});
assert(node('[data-craft-action="craft"]').disabled); // costs 350, only 100 available
assert(node('#craft-blocked').textContent.includes('Недостаточно колец'));
vm.runInContext("craftingKind='upgrade';craftingSelection='1';craftingData.wallet={totalCopper:1000}",ctx);
(async()=>{
  const action=click({craftAction:'upgrade',inventory:'1'});
  const first=events.click(action);
  await events.click(action);
  assert.equal(requests.filter(r=>r.options).length,1,'busy guard prevents duplicate upgrade');
  const sent=JSON.parse(requests[0].options.body);
  assert.equal(sent.action,'upgrade');assert.equal(sent.inventoryId,1);assert.equal(sent.quantity,1);
  assert(!('cost' in sent));assert(!('result' in sent));
  respond({...data,message:'Предмет улучшен.'});await first;
  assert.equal(vm.runInContext('craftingSelection',ctx),null);
  assert.equal(vm.runInContext('craftingBusy',ctx),false);
  assert(messages.includes('Предмет улучшен.'));
  console.log('Craft UI: forge compare/back, actual modifiers, instant result, recipe lock, funds/material/quantity validation, duplicate request guard OK');
})().catch(error=>{console.error(error);process.exitCode=1});
