/* Paginated master catalogue and category-filtered merchant management. */
let masterShopKey='consumables',masterShopCategory='',masterShopQuality='',masterShopQuery='',masterCatalog=null,catalogOffset=0;
document.querySelector('.admin-top>div').insertAdjacentHTML('afterbegin','<button data-open-catalog>КАТАЛОГ</button>');
function masterShopURL(q=masterShopQuery){return `${base()}/shop?${new URLSearchParams({shopKey:masterShopKey,category:masterShopCategory,quality:masterShopQuality,q})}`}
openMasterShop=async function(){try{masterShop=await request(masterShopURL());renderMasterShop()}catch(e){toast(e.message)}};
const oldRenderMasterShop=renderMasterShop;
renderMasterShop=function(){oldRenderMasterShop();const box=$('#editor .admin-box');box.insertAdjacentHTML('afterbegin',`<nav class="merchant-nav">${masterShop.shops.map(s=>`<button class="${s.key===masterShopKey?'active':''}" data-master-merchant="${s.key}">${esc(s.name)}</button>`).join('')}</nav><div class="merchant-filters"><select id="master-shop-category"><option value="">Все категории</option>${masterShop.categories.map(c=>`<option ${c===masterShopCategory?'selected':''}>${esc(c)}</option>`).join('')}</select><select id="master-shop-quality"><option value="">Любое качество</option>${masterShop.qualities.map(c=>`<option ${c===masterShopQuality?'selected':''}>${esc(c)}</option>`).join('')}</select><button data-open-catalog>ПОЛНЫЙ КАТАЛОГ</button></div><p>Обычные лавки: только неуникальные предметы обычного качества. Запас конечный; пополняется мастером. Аксессуаров в стартовых лавках нет.</p>`);$('#shop-filter').value=masterShopQuery};
editMasterShop=async function(payload){try{masterShop=await request(masterShopURL(),{method:'POST',body:JSON.stringify({...payload,shopKey:masterShopKey})});renderMasterShop();toast('Магазин сохранён.')}catch(e){toast(e.message)}};
async function openItemCatalog(offset=0,filters=null){try{const params=filters||masterCatalog?.filters||{q:'',category:'',quality:'',sort:'name',minPrice:'0',maxPrice:'2000000000'};const result=await request(`${base()}/catalog?${new URLSearchParams({...params,offset})}`);masterCatalog={...result,filters:params};catalogOffset=offset;renderItemCatalog()}catch(e){toast(e.message)}}
function renderItemCatalog(){const f=masterCatalog.filters;campaignWorkspace(`<header class="editor-head"><div><small>ПОЛНЫЙ АРХИВ ПРЕДМЕТОВ</small><h1>Каталог</h1><p>Найдено: ${masterCatalog.total}. Цены в медных кольцах. Нажмите на предмет для описания, истории и характеристик.</p></div></header><section class="admin-box"><form id="master-catalog-filters" class="merchant-filters"><input name="q" value="${esc(f.q)}" placeholder="Название или описание"><select name="category" aria-label="Категория"><option value="">Все категории</option>${masterCatalog.categories.map(c=>`<option ${c===f.category?'selected':''}>${esc(c)}</option>`).join('')}</select><select name="quality" aria-label="Качество"><option value="">Любое качество</option>${masterCatalog.qualities.map(c=>`<option ${c===f.quality?'selected':''}>${esc(c)}</option>`).join('')}</select><select name="sort" aria-label="Сортировка">${[['name','По названию'],['price_asc','Сначала дешёвые'],['price_desc','Сначала дорогие']].map(([k,v])=>`<option value="${k}" ${k===f.sort?'selected':''}>${v}</option>`).join('')}</select><label>Цена от<input name="minPrice" type="number" min="0" value="${esc(f.minPrice)}"></label><label>до<input name="maxPrice" type="number" min="0" value="${esc(f.maxPrice)}"></label><button class="action">НАЙТИ</button></form><div class="item-catalog-grid">${masterCatalog.items.map(i=>`<button class="catalog-card" data-catalog-detail="${i.id}"><img data-quality="${esc(i.quality)}" src="${esc(i.image_url)}" alt="${esc(i.name)}" title="${i.iconFallback?'Значок категории':'Иконка из игры'}"><b>${esc(i.name)}</b><span>${esc(i.category)} · ${esc(i.quality)}</span><span>${i.value} медных · ${esc(i.slot||'Без слота')}</span></button>`).join('')||'<p>Предметов по этим фильтрам нет.</p>'}</div><nav class="merchant-nav"><button data-catalog-page="${Math.max(0,catalogOffset-50)}" ${catalogOffset===0?'disabled':''}>НАЗАД</button><span>${masterCatalog.total?catalogOffset+1:0}–${Math.min(catalogOffset+50,masterCatalog.total)} из ${masterCatalog.total}</span><button data-catalog-page="${catalogOffset+50}" ${catalogOffset+50>=masterCatalog.total?'disabled':''}>ДАЛЕЕ</button></nav></section><dialog id="catalog-detail"><div id="catalog-detail-body"></div><button data-close-catalog-detail>ЗАКРЫТЬ</button></dialog>`)}
document.addEventListener('submit',e=>{if(e.target.id==='master-catalog-filters'){e.preventDefault();openItemCatalog(0,Object.fromEntries(new FormData(e.target)))}});
document.addEventListener('click',e=>{if(e.target.closest('[data-open-catalog]'))openItemCatalog();const page=e.target.closest('[data-catalog-page]');if(page)openItemCatalog(+page.dataset.catalogPage);const merchant=e.target.closest('[data-master-merchant]');if(merchant){masterShopKey=merchant.dataset.masterMerchant;masterShopCategory='';masterShopQuality='';masterShopQuery='';openMasterShop()}const detailButton=e.target.closest('[data-catalog-detail]');if(detailButton){const i=masterCatalog.items.find(r=>r.id===+detailButton.dataset.catalogDetail);$('#catalog-detail-body').innerHTML=`<h2>${esc(i.name)}</h2><img class="catalog-detail-icon" src="${esc(i.image_url)}" alt="${esc(i.name)}"><p>${esc(i.category)} · ${esc(i.quality)} · ${i.value} медных</p>${i.iconFallback?'<p>Оригинальная иконка не найдена — показан значок категории.</p>':''}<h3>Описание</h3><p class="item-description">${esc(i.description||'Описание отсутствует в данных.')}</p><h3>История</h3><p class="item-description">${esc(i.lore||'')}</p><h3>Характеристики</h3><p>Слот: ${esc(i.slot||'—')} · Вес: ${i.weight} · Рук: ${i.hands||0}<br>Урон: ${i.damage_min||0}–${i.damage_max||0} · Броня: ${i.armor||0} · Восстановление: ${i.recovery||0}</p><pre>${esc(Object.entries(i.properties||{}).filter(([k])=>k!=='gameData').map(([k,v])=>`${k}: ${typeof v==='object'?JSON.stringify(v):v}`).join('\n'))}</pre>`;$('#catalog-detail').showModal()}if(e.target.closest('[data-close-catalog-detail]'))$('#catalog-detail').close()});
document.addEventListener('change',e=>{if(e.target.id==='master-shop-category'){masterShopCategory=e.target.value;openMasterShop()}if(e.target.id==='master-shop-quality'){masterShopQuality=e.target.value;openMasterShop()}});
document.addEventListener('input',e=>{if(e.target.id==='shop-filter')masterShopQuery=e.target.value});
