const q=new URLSearchParams(location.search),h=new URLSearchParams(location.hash.slice(1)),api=(q.get('api')||localStorage.getItem('tyranny_api')||'').replace(/\/$/,''),token=h.get('token')||q.get('token')||'';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let archive=[],data=null,tab='overview'; if(api)localStorage.setItem('tyranny_api',api);
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3500)};
async function request(path,opt={}){const r=await fetch(api+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`Ошибка ${r.status}`);return j}
function normalize(j={}){return {...j,character:{attributes:{},skills:{},talents:[],...(j.character||{})},inventory:Array.isArray(j.inventory)?j.inventory:[],spells:Array.isArray(j.spells)?j.spells:[],talentLibrary:Array.isArray(j.talentLibrary)?j.talentLibrary:[],factionTalents:Array.isArray(j.factionTalents)?j.factionTalents:[],reputations:j.reputations||{},abilityDetails:j.abilityDetails||{},sigils:{cores:[],expressions:[],accents:[],enhancements:[],...(j.sigils||{})},equipmentSlots:Array.isArray(j.equipmentSlots)?j.equipmentSlots:[],attributeDetails:j.attributeDetails||{},skillAttributes:j.skillAttributes||{},derived:{defenses:{},cooldownMultiplier:1,cooldownPercent:0,equipmentRecovery:0,...(j.derived||{})},capacity:{used:0,capacity:0,athletics:0,...(j.capacity||{})}}}
function tip(name,text){return `<span class="tip" title="${esc(text)}">${esc(name)}</span>`}
async function boot(){if(!api){$('#loading').textContent='Адрес API не указан. Откройте ссылку из Discord.';return}try{const a=await request('/api/archive');archive=Array.isArray(a.characters)?a.characters:[];renderArchive();if(token){data=normalize(await request('/api/portal/'+encodeURIComponent(token)));$('#cabinet-nav').hidden=false;renderCabinet();showView('cabinet')}else showView('archive');$('#loading').hidden=true}catch(e){$('#loading').textContent=e.message}}
function showView(name){$('#archive-view').hidden=name!=='archive';$('#cabinet-view').hidden=name!=='cabinet';document.querySelectorAll('.topbar nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
function renderArchive(){const term=$('#search').value.toLowerCase(),rows=archive.filter(c=>[c.name,c.background,c.specialization_1,c.specialization_2].join(' ').toLowerCase().includes(term));$('#archive-count').textContent=`${rows.length} дел`;$('#archive-grid').innerHTML=rows.map(c=>`<button class="record-card" data-id="${c.id}" style="--portrait:${c.portrait_url?`url('${esc(c.portrait_url)}')`:'linear-gradient(135deg,#351016,#0b0b0d)'}"><div><span class="level">УРОВЕНЬ ${c.level}</span><h2>${esc(c.name)}</h2><p>${esc(c.background)}</p><p>${esc(c.specialization_1)} · ${esc(c.specialization_2)}</p></div></button>`).join('')||'<p>Персонажи не найдены.</p>'}
async function openRecord(id){try{const d=normalize(await request('/api/archive/'+id)),c=d.character;$('#record-body').innerHTML=`<small>ЛИЧНОЕ ДЕЛО · УРОВЕНЬ ${c.level}</small><h1>${esc(c.name)}</h1><p>${esc(c.background)} · ${esc(c.specialization_1)} / ${esc(c.specialization_2)}</p><div class="grid">${statsBox(c,d,false)}${skillsBox(c)}</div>`;$('#record').showModal()}catch(e){toast(e.message)}}
function renderCabinet(){const c=data.character;$('#profile-head').innerHTML=`${c.portrait_url?`<img class="portrait" src="${esc(c.portrait_url)}" alt="">`:''}<div><small>ЛИЧНОЕ ДЕЛО · УРОВЕНЬ ${c.level}</small><h1>${esc(c.name)}</h1><p>${esc(c.background)} · ${esc(c.specialization_1)} / ${esc(c.specialization_2)}</p><b>${c.health}/${c.health_max} здоровья · ${c.experience} опыта</b></div>`;renderTab()}
function statsBox(c,d,editable=true){const details=d.attributeDetails||{};return `<section class="box"><h2>Характеристики</h2>${Object.entries(c.attributes).map(([n,v])=>{const cost=1+Math.floor(Math.max(0,v-9)/10);return `<div class="stat"><div>${tip(n,details[n]?.description||'Базовая характеристика персонажа.')}<small>${esc(details[n]?.effects||'')}</small></div><b class="value">${v}</b>${editable?`<button class="plus" data-attr="${esc(n)}" ${c.attribute_points<cost?'disabled':''}>+${cost}</button>`:''}</div>`}).join('')}${editable?`<p>Свободно: <b>${c.attribute_points}</b></p>`:''}</section>`}
function skillsBox(c){return `<section class="box"><h2>Навыки</h2>${Object.entries(c.skills).sort((a,b)=>b[1].value-a[1].value).map(([n,v])=>`<div class="stat"><div>${tip(n,`База: ${data?.skillAttributes?.[n]?.join(' × 1,5 / × 0,5')||'определяется характеристиками'}; растёт при применении.`)}<div class="meter"><i style="width:${Math.min(100,v.experience%100)}%"></i></div></div><b class="value">${v.value}</b><span>${v.experience} XP</span></div>`).join('')}</section>`}
function abilitiesBox(c){const details=data?.abilityDetails||{},rows=(c?.talents||[]).filter(t=>details[t.name]);if(!rows.length)return'';return `<section class="box"><h2>Способности</h2>${rows.map(t=>{const a=details[t.name]||{},base=parseFloat(a.cooldown),effective=Number.isFinite(base)?(base*(data?.derived?.cooldownMultiplier??1)).toFixed(1)+' сек.':(a.cooldown||'не указана');return `<article class="item">${a.icon?`<img src="${esc(a.icon)}" alt="">`:''}<div><h3>${tip(t.name,a.description||t.description||'')}</h3><p>${esc(a.type||'Способность')} · перезарядка ${effective} (база ${esc(a.cooldown||'не указана')})</p><p>${esc(Array.isArray(a.effects)?a.effects.join(' · '):'')}</p></div></article>`}).join('')}</section>`}
function renderTab(){const c=data.character,p=$('#panel');if(tab==='overview')p.innerHTML=`<div class="grid">${statsBox(c,data)}<section class="box"><h2>Производные значения</h2>${Object.entries(data.derived.defenses).map(([n,v])=>`<div class="stat"><span>${tip(n,'Защита от соответствующего типа атак; рассчитывается из характеристик, навыков, предметов и эффектов.')}</span><b class="value">${v}</b></div>`).join('')}<div class="stat"><span>${tip('Перезарядка','Быстрота изменяет восстановление способностей на 3% за пункт относительно 10.')}</span><b>${data.derived.cooldownPercent>=0?'−':'+'}${Math.abs(data.derived.cooldownPercent)}%</b></div><div class="stat"><span>Восстановление экипировки</span><b>${data.derived.equipmentRecovery} сек.</b></div></section>${abilitiesBox(c)}${skillsBox(c)}</div>`;
 else if(tab==='development')p.innerHTML=`<div class="grid">${statsBox(c,data)}${skillsBox(c)}<section class="box"><h2>Как растёт персонаж</h2><p>За уровень вы получаете одно очко характеристики и одно очко таланта. Навыки в Tyranny растут от успешного применения в бою и диалогах — их нельзя купить очками уровня.</p></section></div>`;
 else if(tab==='talents')renderTalents(p,c);else if(tab==='factions')renderFactions(p,c);else if(tab==='spells')renderSpells(p,c);else renderInventory(p,c)}
function renderTalents(p,c){const owned=new Set((c.talents||[]).map(x=>x.name)),trees={};(data?.talentLibrary||[]).forEach(t=>(trees[t.tree]??=[]).push(t));p.innerHTML=`<p>Свободные очки талантов: <b>${c.talent_points??0}</b> · базовые деревья Вершителя и личные ветки предыстории используют общий запас.</p><div class="talent-trees">${Object.entries(trees).map(([tree,ts])=>`<section class="box"><h2>${esc(tree)}</h2>${ts.map(t=>{const auto=t.automatic_level>0,has=owned.has(t.name)||(auto&&c.level>=t.automatic_level);return `<article class="talent ${has?'owned':''}">${t.icon_url?`<a class="talent-icon" href="${esc(t.source_url)}" target="_blank" rel="noreferrer"><img src="${esc(t.icon_url)}" alt=""></a>`:`<div class="talent-icon">${esc(tree[0])}</div>`}<div><b>${tip(t.name,`${t.name_en?`${t.name_en}. `:''}${t.description}`)}</b><p>${esc(t.description)}</p><small>${auto?`Открывается на ${t.automatic_level} уровне`:`Нужно вложить в ветку: ${t.tier}`}</small></div>${has?'<b>✓</b>':auto?'<b>🔒</b>':`<button class="plus" data-talent="${esc(t.name)}" ${c.talent_points<1?'disabled':''}>+</button>`}</article>`}).join('')}</section>`).join('')||'<section class="box"><p>Справочник талантов временно недоступен. Ваше личное дело продолжает работать.</p></section>'}</div>`}
function renderFactions(p,c){const factions=new Set([...Object.keys(data.reputations),...data.factionTalents.map(t=>t.faction)]);p.innerHTML=`<div class="talent-trees">${[...factions].sort().map(name=>{const rep=data.reputations[name]||{favor:0,wrath:0},favorTier=Math.min(5,Math.floor(rep.favor/20)),wrathTier=Math.min(5,Math.floor(rep.wrath/20)),talents=data.factionTalents.filter(t=>t.faction===name);return `<section class="box"><h2>${esc(name)}</h2><div class="rep-axis"><b>Благосклонность ${rep.favor}/100 · ранг ${favorTier}</b><div class="meter"><i style="width:${rep.favor}%"></i></div></div><div class="rep-axis wrath"><b>Гнев ${rep.wrath}/100 · ранг ${wrathTier}</b><div class="meter"><i style="width:${rep.wrath}%"></i></div></div>${talents.map(t=>{const rank=t.axis==='favor'?favorTier:wrathTier,has=rank>=t.tier;return `<article class="talent ${has?'owned':''}"><a class="talent-icon" href="${esc(t.source_url)}" target="_blank" rel="noreferrer">${t.icon_url?`<img src="${esc(t.icon_url)}" alt="">`:'◆'}</a><div><b>${tip(t.name,`${t.name_en}. ${t.description}`)}</b><p>${esc(t.description)}</p><small>${t.axis==='favor'?'Благосклонность':'Гнев'} · ранг ${t.tier}</small></div><b>${has?'✓':'🔒'}</b></article>`}).join('')||'<p>У этой стороны нет отдельных фракционных талантов.</p>'}</section>`}).join('')}</div>`}
function options(rows){return rows.map(x=>`<option>${esc(x)}</option>`).join('')}
function renderSpells(p,c){p.innerHTML=`<section class="box"><h2>Создать заклинание</h2><div class="spell-form"><label>Название<input id="spell-name"></label><label>Основа<select id="spell-core">${options(data.sigils.cores)}</select></label><label>Выражение<select id="spell-expression">${options(data.sigils.expressions)}</select></label><label>Акцент<select id="spell-accent"><option value="">Нет</option>${options(data.sigils.accents)}</select></label><label>Усиление<select id="spell-enhancement"><option value="">Нет</option>${options(data.sigils.enhancements)}</select></label><label>Сложность<input id="spell-difficulty" type="number" min="0" value="0"></label></div><p>Доступные Знания: <b>${c.skills?.['Знания']?.value??0}</b>. Сложность не может их превышать.</p><button id="save-spell" class="action">ЗАПИСАТЬ ФОРМУЛУ</button></section><section class="box"><h2>Гримуар</h2>${data.spells.map(s=>`<article class="spell-card"><h3>${esc(s.name)} <small>· ${s.difficulty}</small></h3><p>${esc(s.core)} + ${esc(s.expression)}${[...(s.accents||[]),...(s.enhancements||[])].length?' + '+esc([...(s.accents||[]),...(s.enhancements||[])].join(', ')):''}</p></article>`).join('')||'<p>Заклинаний пока нет.</p>'}</section>`}
function renderInventory(p,c){const cap=data.capacity;p.innerHTML=`<p class="capacity">Занято ${cap.used} из ${cap.capacity} слотов · Атлетика ${cap.athletics}. Экипированные и мелкие предметы слотов не занимают.</p><div class="grid"><section class="box"><h2>Экипировано</h2>${items(data.inventory.filter(x=>x.equipped_slot),true)}</section><section class="box"><h2>Сумка</h2>${items(data.inventory.filter(x=>!x.equipped_slot),false)}</section></div>`}
function items(rows,equipped){return rows.map(i=>`<article class="item">${i.image_url?`<img src="${esc(i.image_url)}" alt="">`:`<div class="item-icon">◆</div>`}<div><h3>${esc(i.name)} ×${i.quantity}</h3><p>${esc(i.category)} · ${esc(i.quality)}${i.equipped_slot?' · '+esc(i.equipped_slot):''}</p><p>${esc(i.description)}</p></div><div>${equipped?`<button class="action" data-unequip="${i.inventory_id}">СНЯТЬ</button>`:`<select class="equipment-select" data-equip="${i.inventory_id}"><option value="">Экипировать…</option>${options(data.equipmentSlots)}</select>`}</div></article>`).join('')||'<p>Пусто.</p>'}
async function mutate(path,body){try{const j=await request(`/api/portal/${encodeURIComponent(token)}/${path}`,{method:'POST',body:JSON.stringify(body)});data=normalize(j);toast(j.message);renderCabinet()}catch(e){toast(e.message)}}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v)showView(v.dataset.view);const card=e.target.closest('[data-id]');if(card)openRecord(card.dataset.id);const tabBtn=e.target.closest('[data-tab]');if(tabBtn){tab=tabBtn.dataset.tab;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===tabBtn));renderTab()}const a=e.target.closest('[data-attr]');if(a)mutate('attribute',{name:a.dataset.attr});const t=e.target.closest('[data-talent]');if(t)mutate('talent',{name:t.dataset.talent});const u=e.target.closest('[data-unequip]');if(u)mutate('equipment',{inventoryId:+u.dataset.unequip,unequip:true});if(e.target.id==='save-spell')mutate('spell',{name:$('#spell-name').value,core:$('#spell-core').value,expression:$('#spell-expression').value,accents:[$('#spell-accent').value].filter(Boolean),enhancements:[$('#spell-enhancement').value].filter(Boolean),difficulty:+$('#spell-difficulty').value})});
document.addEventListener('change',e=>{if(e.target.matches('[data-equip]')&&e.target.value)mutate('equipment',{inventoryId:+e.target.dataset.equip,slot:e.target.value})});$('#search').addEventListener('input',renderArchive);$('#record .close').onclick=()=>$('#record').close();boot();
