const q=new URLSearchParams(location.search),h=new URLSearchParams(location.hash.slice(1)),api=(q.get('api')||localStorage.getItem('tyranny_api')||'').replace(/\/$/,''),token=h.get('token')||q.get('token')||'';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roundText=n=>{const v=Number(n)||0,r=v/10,s=Number.isInteger(r)?String(r):r.toFixed(2).replace(/0+$/,'').replace(/\.$/,'').replace('.',','),w=Number.isInteger(r)&&r%10===1&&r%100!==11?'раунд':Number.isInteger(r)&&[2,3,4].includes(r%10)&&![12,13,14].includes(r%100)?'раунда':'раундов';return `${s} ${w}`};
const scaledRoundText=n=>{const r=Number(n)||0,s=Number.isInteger(r)?String(r):r.toFixed(2).replace(/0+$/,'').replace(/\.$/,'').replace('.',','),w=Number.isInteger(r)&&r%10===1&&r%100!==11?'раунд':Number.isInteger(r)&&[2,3,4].includes(r%10)&&![12,13,14].includes(r%100)?'раунда':'раундов';return `${s} ${w}`};
let archive=[],data=null,training=null,trainingLoading=false,tab='overview',selectedTalentName='',selectedSigilKey='';
let spellSelection={core:'',expression:'',accents:new Set(),enhancement:''}; if(api)localStorage.setItem('tyranny_api',api);
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3500)};
async function request(path,opt={}){const r=await fetch(api+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`Ошибка ${r.status}`);return j}
function normalize(j={}){return {...j,character:{attributes:{},skills:{},talents:[],...(j.character||{})},inventory:Array.isArray(j.inventory)?j.inventory:[],spells:Array.isArray(j.spells)?j.spells:[],talentLibrary:Array.isArray(j.talentLibrary)?j.talentLibrary:[],factionTalents:Array.isArray(j.factionTalents)?j.factionTalents:[],reputations:j.reputations||{},abilityDetails:j.abilityDetails||{},sigils:{library:[],knownKeys:[],scrolls:[],...(j.sigils||{})},equipmentSlots:Array.isArray(j.equipmentSlots)?j.equipmentSlots:[],equipmentLimits:{weaponSets:2,quickSlots:4,...(j.equipmentLimits||{})},attributeDetails:j.attributeDetails||{},skillAttributes:j.skillAttributes||{},derived:{defenses:{},attack:{accuracy:0,damageMin:1,damageMax:2,recovery:0,criticalChance:1,skill:'Безоружный бой'},armor:0,deflection:0,activeWeaponSet:1,cooldownMultiplier:1,cooldownPercent:0,equipmentRecovery:0,...(j.derived||{})},capacity:{used:0,capacity:0,athletics:0,...(j.capacity||{})}}}
function tip(name,text){return `<span class="tip" title="${esc(text)}">${esc(name)}</span>`}
async function boot(){if(!api){$('#loading').textContent='Адрес сервера не указан. Откройте ссылку из Дискорда.';return}try{const a=await request('/api/archive');archive=Array.isArray(a.characters)?a.characters:[];renderArchive();if(token){data=normalize(await request('/api/portal/'+encodeURIComponent(token)));$('#cabinet-nav').hidden=false;renderCabinet();showView('cabinet')}else showView('archive');$('#loading').hidden=true}catch(e){$('#loading').textContent=e.message}}
function showView(name){$('#archive-view').hidden=name!=='archive';$('#cabinet-view').hidden=name!=='cabinet';document.querySelectorAll('.topbar nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
function renderArchive(){const term=$('#search').value.toLowerCase(),rows=archive.filter(c=>[c.name,c.background,c.specialization_1,c.specialization_2].join(' ').toLowerCase().includes(term));$('#archive-count').textContent=`${rows.length} дел`;$('#archive-grid').innerHTML=rows.map(c=>`<button class="record-card" data-id="${c.id}" style="--portrait:${c.portrait_url?`url('${esc(c.portrait_url)}')`:'linear-gradient(135deg,#351016,#0b0b0d)'}"><div><span class="level">УРОВЕНЬ ${c.level}</span><h2>${esc(c.name)}</h2><p>${esc(c.background)}</p><p>${esc(c.specialization_1)} · ${esc(c.specialization_2)}</p></div></button>`).join('')||'<p>Персонажи не найдены.</p>'}
async function openRecord(id){try{const d=normalize(await request('/api/archive/'+id)),c=d.character;$('#record-body').innerHTML=`<small>ЛИЧНОЕ ДЕЛО · УРОВЕНЬ ${c.level}</small><h1>${esc(c.name)}</h1><p>${esc(c.background)} · ${esc(c.specialization_1)} / ${esc(c.specialization_2)}</p><div class="grid">${statsBox(c,d,false)}${skillsBox(c)}</div>`;$('#record').showModal()}catch(e){toast(e.message)}}
function renderCabinet(){const c=data.character;$('#profile-head').innerHTML=`${c.portrait_url?`<img class="portrait" src="${esc(c.portrait_url)}" alt="">`:''}<div><small>ЛИЧНОЕ ДЕЛО · УРОВЕНЬ ${c.level}</small><h1>${esc(c.name)}</h1><p>${esc(c.background)} · ${esc(c.specialization_1)} / ${esc(c.specialization_2)}</p><b>${c.health}/${c.health_max} здоровья · ${c.experience} опыта</b></div>`;renderTab()}
function statsBox(c,d,editable=true){const details=d.attributeDetails||{};return `<section class="box"><h2>Характеристики</h2>${Object.entries(c.attributes).map(([n,v])=>{const cost=1+Math.floor(Math.max(0,v-9)/10);return `<div class="stat"><div>${tip(n,details[n]?.description||'Базовая характеристика персонажа.')}<small>${esc(details[n]?.effects||'')}</small></div><b class="value">${v}</b>${editable?`<button class="plus" data-attr="${esc(n)}" ${c.attribute_points<cost?'disabled':''}>+${cost}</button>`:''}</div>`}).join('')}${editable?`<p>Свободно: <b>${c.attribute_points}</b></p>`:''}</section>`}
function skillsBox(c){return `<section class="box"><h2>Навыки</h2>${Object.entries(c.skills).sort((a,b)=>b[1].value-a[1].value).map(([n,v])=>`<div class="stat"><div>${tip(n,`База: ${data?.skillAttributes?.[n]?.join(' × 1,5 / × 0,5')||'определяется характеристиками'}; растёт при применении.`)}<div class="meter"><i style="width:${Math.min(100,v.experience%100)}%"></i></div></div><b class="value">${v.value}</b><span>${v.experience} ОПЫТА</span></div>`).join('')}</section>`}
function abilitiesBox(c){const details=data?.abilityDetails||{},rows=(c?.talents||[]).filter(t=>details[t.name]);if(!rows.length)return'';return `<section class="box"><h2>Способности</h2>${rows.map(t=>{const a=details[t.name]||{},base=parseFloat(a.cooldown),effective=Number.isFinite(base)?scaledRoundText(base*(data?.derived?.cooldownMultiplier??1)):(a.cooldown||'не указана');return `<article class="item">${a.icon?`<img src="${esc(a.icon)}" alt="">`:''}<div><h3>${tip(t.name,a.description||t.description||'')}</h3><p>${esc(a.type||'Способность')} · перезарядка ${effective} (база ${esc(a.cooldown||'не указана')})</p><p>${esc(Array.isArray(a.effects)?a.effects.join(' · '):'')}</p></div></article>`}).join('')}</section>`}
function renderTab(){const c=data.character,p=$('#panel');if(tab==='overview')p.innerHTML=`<div class="grid">${statsBox(c,data)}<section class="box"><h2>Производные значения</h2>${Object.entries(data.derived.defenses).map(([n,v])=>`<div class="stat"><span>${tip(n,'Защита от соответствующего типа атак; рассчитывается из характеристик, навыков, предметов и эффектов.')}</span><b class="value">${v}</b></div>`).join('')}<div class="stat"><span>${tip('Перезарядка','Быстрота изменяет восстановление способностей на 3% за пункт относительно 10.')}</span><b>${data.derived.cooldownPercent>=0?'−':'+'}${Math.abs(data.derived.cooldownPercent)}%</b></div><div class="stat"><span>Восстановление экипировки</span><b>${roundText(data.derived.equipmentRecovery)}</b></div></section>${abilitiesBox(c)}${skillsBox(c)}</div>`;
 else if(tab==='development')p.innerHTML=`<div class="grid">${statsBox(c,data)}${skillsBox(c)}<section class="box"><h2>Как растёт персонаж</h2><p>За уровень вы получаете одно очко характеристики и одно очко таланта. Навыки в «Тирании» растут от успешного применения в бою и диалогах — их нельзя купить очками уровня.</p></section></div>`;
 else if(tab==='talents')renderTalents(p,c);else if(tab==='factions')renderFactions(p,c);else if(tab==='spells')renderSpells(p,c);else if(tab==='training')renderTraining(p,c);else renderInventory(p,c)}

async function loadTraining(){if(trainingLoading)return;trainingLoading=true;try{const j=await request(`/api/portal/${encodeURIComponent(token)}/training`);training=j.training||{active:false}}catch(e){toast(e.message);training={active:false}}finally{trainingLoading=false;if(tab==='training')renderTraining($('#panel'),data.character)}}
function hpBar(current,max){const percent=Math.max(0,Math.min(100,Number(current||0)/Math.max(1,Number(max||1))*100));return `<div class="fight-hp"><i style="width:${percent}%"></i><b>${current} / ${max}</b></div>`}
function renderTraining(p,c){
 if(training===null){p.innerHTML='<section class="training-intro"><div class="training-rune">⚔</div><h2>Подготавливаем тренировочную арену…</h2></section>';loadTraining();return}
 if(!training.active){p.innerHTML=`<section class="training-intro"><small>ПОШАГОВАЯ ТРЕНИРОВКА</small><div class="training-rune">⚔</div><h2>Испытайте свой билд</h2><p>Сразитесь с укреплённым манекеном. Сервер использует настоящие характеристики, экипировку, активный комплект оружия, способности, заклинания и перезарядки персонажа.</p><b>Здоровье, расходники, опыт навыков и опыт персонажа не изменяются.</b><button class="action training-start">НАЧАТЬ ТРЕНИРОВКУ</button></section>`;return}
 const t=training,d=t.derived||{},a=d.attack||{},dummy=t.dummy||{},summary=t.summary||{},portrait=t.character?.portraitUrl||c.portrait_url;
 const actions=(t.actions||[]).map(x=>`<button class="training-action ${x.kind}" data-training-kind="${esc(x.kind)}" data-training-name="${esc(x.name)}" ${(x.remaining||t.finished)?'disabled':''}>${x.icon?`<img src="${esc(x.icon)}" alt="">`:'<span>◆</span>'}<div><b>${esc(x.name)}</b><small>${esc(x.description||'')}</small>${x.remaining?`<em>Готово через ${x.remaining} раунд.</em>`:x.cooldown?`<em>Перезарядка: ${esc(x.cooldown)}</em>`:'<em>Доступно</em>'}</div></button>`).join('');
 const sets=Array.from({length:t.character?.weaponSets||1},(_,i)=>`<button class="training-set ${i+1===t.character.activeWeaponSet?'active':''}" data-training-set="${i+1}" ${t.finished?'disabled':''}>${['I','II','III','IV'][i]}</button>`).join('');
 p.innerHTML=`<section class="training-screen"><header class="training-header"><div><small>ТРЕНИРОВОЧНЫЙ БОЙ · НАГРАДЫ ОТКЛЮЧЕНЫ</small><h2>Раунд ${t.round}</h2></div><button class="training-reset">ЗАВЕРШИТЬ</button></header><div class="training-stage"><article class="fighter player">${portrait?`<img src="${esc(portrait)}" alt="${esc(c.name)}">`:`<div class="fighter-rune">${esc(c.name[0]||'Ж')}</div>`}<h3>${esc(c.name)}</h3>${hpBar(c.health,c.health_max)}<p>Точность ${a.accuracy||0} · урон ${a.damageMin||0}–${a.damageMax||0} · броня ${d.armor||0}</p><div class="training-sets"><span>Комплект</span>${sets}</div></article><div class="turn-seal"><b>${t.finished?'ПОБЕДА':'ВАШ ХОД'}</b><span>${t.finished?'Манекен разрушен':'Выберите одно действие'}</span></div><article class="fighter dummy ${t.finished?'destroyed':''}"><div class="dummy-figure"><i></i><i></i><i></i></div><h3>${esc(dummy.name||'Манекен')}</h3>${hpBar(dummy.health,dummy.healthMax)}<p>Броня ${dummy.armor||0} · Парирование ${dummy.defenses?.['Парирование']||0} · Магия ${dummy.defenses?.['Магия']||0}</p></article></div><div class="training-lower"><section class="training-actions"><h3>Действия</h3>${t.finished?'<button class="action training-start">НОВАЯ ТРЕНИРОВКА</button>':actions+'<button class="training-wait" data-training-kind="wait">ПРОПУСТИТЬ ХОД</button>'}</section><aside class="training-report"><h3>Отчёт</h3><div class="training-summary"><b>${summary.damage||0}<small>урона</small></b><b>${summary.hits||0}/${summary.attacks||0}<small>попаданий</small></b><b>${summary.accuracy||0}%<small>точность</small></b></div><ol>${(t.log||[]).map(line=>`<li>${esc(line)}</li>`).join('')}</ol><p>Опыт: <b>0</b> · добыча: <b>нет</b></p></aside></div></section>`;
}
async function trainingMutate(path,body={}){try{const j=await request(`/api/portal/${encodeURIComponent(token)}/training/${path}`,{method:'POST',body:JSON.stringify(body)});training=j.training||{active:false};toast(j.message);if(tab==='training')renderTraining($('#panel'),data.character)}catch(e){toast(e.message)}}
function localTalentIcon(url){if(!url)return'';try{const parts=decodeURIComponent(new URL(url,location.href).pathname).split('/'),revision=parts.indexOf('revision'),filename=parts[revision>0?revision-1:parts.length-1].replace(/[\s_]+/g,'_');return `assets/talent-icons/${encodeURIComponent(filename)}`}catch{return url}}
function talentIcon(t,kind=''){const letter=(t.name||'?').trim()[0]||'?';return `<span class="talent-game-icon ${kind}"><span class="talent-fallback">${esc(letter)}</span>${t.icon_url?`<img src="${esc(localTalentIcon(t.icon_url))}" alt="" loading="lazy" onerror="this.remove()">`:''}</span>`}
function talentInfo(name,c=data?.character){const talent=(data?.talentLibrary||[]).find(t=>t.name===name);if(!talent)return null;const owned=new Set((c?.talents||[]).map(x=>x.name)),automatic=Number(talent.automatic_level||0),has=owned.has(talent.name)||(automatic>0&&c.level>=automatic),spent=(c?.talents||[]).filter(x=>x.tree_name===talent.tree||x.tree===talent.tree).length,needed=Math.max(0,Number(talent.tier||0)-spent);return {talent,automatic,has,spent,needed,canBuy:!has&&!automatic&&needed===0&&Number(c?.talent_points||0)>0}}
function talentSelection(name,c){const s=talentInfo(name,c);if(!s)return '<section id="talent-selection" class="talent-selection"><p>Выберите талант в одном из деревьев.</p></section>';const t=s.talent,requirement=s.has?'Талант изучен':s.automatic?`Открывается автоматически на ${s.automatic} уровне`:s.needed?`Нужно ещё вложить в ветку: ${s.needed}`:'Доступен для изучения';return `<section id="talent-selection" class="talent-selection">${talentIcon(t,'large')}<div><small>${esc(t.tree)} · ступень ${t.tier}</small><h2>${esc(t.name)}</h2><b class="talent-requirement ${s.canBuy?'ready':''}">${esc(requirement)}</b><p>${esc(t.description)}</p></div><div class="talent-actions"><button class="talent-more" data-talent-details="${esc(t.name)}">ПОДРОБНОСТИ</button>${s.canBuy?`<button class="action" data-talent="${esc(t.name)}">ИЗУЧИТЬ</button>`:''}</div></section>`}
function renderTalents(p,c){const trees={};(data?.talentLibrary||[]).forEach(t=>(trees[t.tree]??=[]).push(t));const entries=Object.entries(trees);if(!entries.length){p.innerHTML='<section class="box"><p>Справочник талантов временно недоступен. Ваше личное дело продолжает работать.</p></section>';return}if(!entries.some(([,ts])=>ts.some(t=>t.name===selectedTalentName)))selectedTalentName=entries[0][1][0]?.name||'';p.innerHTML=`<div class="talent-heading"><p>Свободные очки талантов: <b>${c.talent_points??0}</b><small>Базовые деревья Вершителя и личные ветки предыстории используют общий запас.</small></p></div><div class="talent-carousel"><button class="talent-arrow prev" data-scroll-talents="-1" aria-label="Предыдущие ветки">‹</button><div class="talent-track">${entries.map(([tree,ts])=>{const spent=(c.talents||[]).filter(x=>x.tree_name===tree||x.tree===tree).length,tiers=[...new Set(ts.map(t=>Number(t.tier||0)))].sort((a,b)=>a-b);return `<section class="talent-tree"><header><h2>${esc(tree)}</h2><b>${spent}</b></header><div class="talent-lanes">${tiers.map(tier=>`<div class="talent-tier"><span>${tier}</span><div>${ts.filter(t=>Number(t.tier||0)===tier).map(t=>{const s=talentInfo(t.name,c),state=s.has?'owned':s.canBuy?'available':'locked';return `<button class="talent-node ${state} ${t.name===selectedTalentName?'selected':''}" data-select-talent="${esc(t.name)}" title="${esc(t.name)}">${talentIcon(t)}</button>`}).join('')}</div></div>`).join('')}</div></section>`}).join('')}</div><button class="talent-arrow next" data-scroll-talents="1" aria-label="Следующие ветки">›</button></div>${talentSelection(selectedTalentName,c)}`}
function selectTalent(name){selectedTalentName=name;document.querySelectorAll('.talent-node').forEach(n=>n.classList.toggle('selected',n.dataset.selectTalent===name));const old=$('#talent-selection');if(old)old.outerHTML=talentSelection(name,data.character)}
function openTalentDetails(name){const s=talentInfo(name),t=s?.talent;if(!t)return;const requirement=s.has?'Изучен':s.automatic?`Автоматически открывается на ${s.automatic} уровне`:`Требуется ${t.tier} очк. в ветке; вложено ${s.spent}`;$('#talent-dialog-body').innerHTML=`<div class="talent-dialog-head">${talentIcon(t,'large')}<div><small>${esc(t.tree)}</small><h2>${esc(t.name)}</h2></div></div><div class="talent-divider"></div><p class="talent-dialog-requirement">ТРЕБОВАНИЯ: <b>${esc(requirement)}</b></p><p class="talent-dialog-description">${esc(t.description)}</p>${t.source_url?`<a class="wiki-link" href="${esc(t.source_url)}" target="_blank" rel="noreferrer">ОТКРЫТЬ ИСТОЧНИК ↗</a>`:''}`;$('#talent-dialog').showModal()}
function renderFactions(p,c){const factions=new Set([...Object.keys(data.reputations),...data.factionTalents.map(t=>t.faction)]);p.innerHTML=`<div class="talent-trees">${[...factions].sort().map(name=>{const rep=data.reputations[name]||{favor:0,wrath:0},favorTier=Math.min(5,Math.floor(rep.favor/20)),wrathTier=Math.min(5,Math.floor(rep.wrath/20)),talents=data.factionTalents.filter(t=>t.faction===name);return `<section class="box"><h2>${esc(name)}</h2><div class="rep-axis"><b>Благосклонность ${rep.favor}/100 · ранг ${favorTier}</b><div class="meter"><i style="width:${rep.favor}%"></i></div></div><div class="rep-axis wrath"><b>Гнев ${rep.wrath}/100 · ранг ${wrathTier}</b><div class="meter"><i style="width:${rep.wrath}%"></i></div></div>${talents.map(t=>{const rank=t.axis==='favor'?favorTier:wrathTier,has=rank>=t.tier;return `<article class="talent ${has?'owned':''}">${talentIcon(t)}<div><b>${tip(t.name,t.description)}</b><p>${esc(t.description)}</p><small>${t.axis==='favor'?'Благосклонность':'Гнев'} · ранг ${t.tier}</small></div><b>${has?'✓':'🔒'}</b></article>`}).join('')||'<p>У этой стороны нет отдельных фракционных талантов.</p>'}</section>`}).join('')}</div>`}
function sigilIcon(s,small=''){return `<span class="sigil-icon ${small}"><b>${esc((s?.name||'?')[0])}</b>${s?.image_url?`<img src="${esc(s.image_url)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}</span>`}
function spellSigil(key){return (data?.sigils?.library||[]).find(s=>s.key===key)}
function selectedSpellSigils(){return [spellSigil(spellSelection.core),spellSigil(spellSelection.expression),...[...spellSelection.accents].map(spellSigil),spellSigil(spellSelection.enhancement)].filter(Boolean)}
function spellFormulaState(c){const core=spellSigil(spellSelection.core),expression=spellSigil(spellSelection.expression),accents=[...spellSelection.accents].map(spellSigil).filter(Boolean),enhancement=spellSigil(spellSelection.enhancement),lore=Number(c.skills?.['Знания']?.value||0);let error='';if(!core||!expression)error='Выберите основу и выражение.';else if(expression.compatibleCores?.length&&!expression.compatibleCores.includes(core.name))error=`${expression.name} несовместимо с основой «${core.name}».`;else if(enhancement?.compatibleCores?.length&&!enhancement.compatibleCores.includes(core.name))error=`${enhancement.name} несовместимо с этой основой.`;else if(enhancement?.compatibleExpressions?.length&&!enhancement.compatibleExpressions.includes(expression.name))error=`${enhancement.name} несовместимо с этим выражением.`;const difficulty=Number(expression?.lore||0)+accents.reduce((n,s)=>n+Number(s.lore||0),0)+Number(enhancement?.lore||0);if(!error&&difficulty>lore)error=`Нужно Знаний: ${difficulty}; доступно: ${lore}.`;return {core,expression,accents,enhancement,difficulty,lore,error,ready:!!core&&!!expression&&!error}}
function sigilTile(s){const selected=s.key===spellSelection.core||s.key===spellSelection.expression||spellSelection.accents.has(s.key)||s.key===spellSelection.enhancement,locked=!s.known;return `<button class="sigil-tile ${selected?'selected':''} ${locked?'locked':''}" data-sigil-key="${esc(s.key)}" title="${esc(locked?'Нужен соответствующий свиток':`${s.name}: ${s.effect}`)}">${sigilIcon(s)}${s.tier?`<i>${['','I','II','III','IV','V'][s.tier]}</i>`:''}<small>${locked?'🔒':s.lore?`${s.lore} ЗН.`:'ИЗУЧЕН'}</small></button>`}
function sigilGroup(title,type){const rows=(data.sigils.library||[]).filter(s=>s.type===type);return `<section class="sigil-palette"><h3>${title}</h3><div class="sigil-grid">${rows.map(sigilTile).join('')}</div></section>`}
function selectedSigilPanel(){const s=spellSigil(selectedSigilKey)||selectedSpellSigils().at(-1);if(!s)return `<div class="sigil-details empty"><p>Выберите символ, чтобы прочитать его описание.</p></div>`;return `<div class="sigil-details">${sigilIcon(s,'large')}<div><small>${({core:'ОСНОВА',expression:'ВЫРАЖЕНИЕ',accent:'АКЦЕНТ',enhancement:'УСИЛЕНИЕ'})[s.type]}${s.tier?` · УРОВЕНЬ ${s.tier}`:''}</small><h3>${esc(s.name)}</h3><p>${esc(s.effect)}</p><b>${s.known?'ИЗУЧЕН':`НУЖЕН СВИТОК`} ${s.lore?`· ${s.lore} ЗНАНИЙ`:''}</b>${s.source_url?`<a href="${esc(s.source_url)}" target="_blank" rel="noreferrer">ВИКИ ↗</a>`:''}</div></div>`}
function learnedScrolls(){const scrolls=data.sigils.scrolls||[];if(!scrolls.length)return '<p class="empty-scrolls">В инвентаре нет неизученных свитков сигилов.</p>';return scrolls.map(row=>`<article class="sigil-scroll ${row.known?'known':''}">${sigilIcon(row.sigil)}<div><small>СВИТОК · ${row.quantity} ШТ.</small><b>${esc(row.sigil.name)}${row.sigil.tier?` ${['','I','II','III','IV','V'][row.sigil.tier]}`:''}</b><p>${esc(row.sigil.effect)}</p></div>${row.known?'<span>ИЗУЧЕН</span>':`<button class="action" data-learn-sigil="${row.inventoryId}">ИЗУЧИТЬ</button>`}</article>`).join('')}
function renderSpells(p,c){const state=spellFormulaState(c),chosen=selectedSpellSigils();p.innerHTML=`<section class="spell-workbench"><div class="spell-builder"><header><div><small>КОНСТРУКТОР ЗАКЛИНАНИЙ</small><h2>Сигилы формулы</h2></div><div class="lore-seal"><span>ЗНАНИЯ</span><b>${state.difficulty} / ${state.lore}</b></div></header><div class="spell-palette-row">${sigilGroup('ОСНОВЫ','core')}${sigilGroup('ВЫРАЖЕНИЯ','expression')}</div><div class="spell-palette-row lower">${sigilGroup('ДОПОЛНИТЕЛЬНЫЕ СИМВОЛЫ','accent')}${sigilGroup('СИМВОЛЫ УСИЛЕНИЯ','enhancement')}</div>${selectedSigilPanel()}<div class="formula-bar"><div class="formula-slots"><span class="formula-slot">${state.core?sigilIcon(state.core,'small'):'+'}</span><span>+</span><span class="formula-slot">${state.expression?sigilIcon(state.expression,'small'):'+'}</span>${state.accents.map(s=>`<span>+</span><span class="formula-slot">${sigilIcon(s,'small')}</span>`).join('')}${state.enhancement?`<span>+</span><span class="formula-slot enhanced">${sigilIcon(state.enhancement,'small')}</span>`:''}</div><label>Название формулы<input id="spell-name" maxlength="80" placeholder="Оставьте пустым для канонического названия"></label><p class="formula-status ${state.error?'bad':'good'}">${esc(state.error||`Формула доступна · сложность ${state.difficulty}`)}</p><div><button class="sigil-reset">СБРОСИТЬ</button><button id="save-spell" class="action" ${state.ready?'':'disabled'}>СОЗДАТЬ ЗАКЛИНАНИЕ</button></div></div></div><aside class="spellbook"><header><small>ФОРМУЛЫ ПЕРСОНАЖА</small><h2>Гримуар</h2></header>${data.spells.map(s=>`<article class="spell-card"><span class="spell-rune">✦</span><div><h3>${esc(s.name)}</h3><p>${esc(s.core)} · ${esc(s.expression)}</p><small>${[...(s.accents||[]),...(s.enhancements||[])].map(esc).join(' · ')||'Без дополнительных символов'}</small></div><b>${s.difficulty}<small>ЗН.</small></b></article>`).join('')||'<p class="empty-grimoire">В гримуаре пока нет формул.</p>'}</aside></section><section class="sigil-scroll-case box"><header><div><small>ИНВЕНТАРЬ ЗНАНИЙ</small><h2>Свитки сигилов</h2></div><p>Изучение расходует один свиток и навсегда открывает символ персонажу.</p></header><div class="sigil-scroll-list">${learnedScrolls()}</div></section>`}
function itemVisual(i){const letter=(i?.name||'?')[0]||'?';return `<span class="gear-art"><i>${esc(letter)}</i>${i?.image_url?`<img src="${esc(i.image_url)}" alt="" referrerpolicy="no-referrer" loading="lazy" onerror="this.remove()">`:''}</span>`}
function equipmentSlot(slot,label,position,bySlot){const item=bySlot[slot];return `<div class="paper-slot ${position}"><b>${esc(label)}</b><button ${item?`data-item-details="${item.inventory_id}"`:''} title="${esc(item?.name||slot)}">${item?itemVisual(item):'<span class="empty-rune">◇</span>'}</button></div>`}
function statIcon(file,label,value,help=''){return `<div class="combat-stat" title="${esc(help||label)}"><img src="assets/stat-icons/${file}" alt=""><span>${esc(label)}</span><b>${esc(value)}</b></div>`}
function compatibleSlots(i){const limits=data.equipmentLimits,slots=[];if(i.category==='Броня')return i.slot?[i.slot]:['Голова','Торс','Руки','Ноги'];if(i.category==='Аксессуары')return['Аксессуар 1','Аксессуар 2'];if(['Расходуемые предметы','Зелья','Еда'].includes(i.category))return Array.from({length:limits.quickSlots},(_,n)=>`Быстрый предмет ${n+1}`);if(['Одноручное оружие','Двуручное оружие','Парное оружие','Луки','Метательное оружие','Посохи','Щиты'].includes(i.category)){for(let n=1;n<=limits.weaponSets;n++){const r=['I','II','III','IV'][n-1];if(i.category!=='Щиты')slots.push(`Оружие ${r} — правая рука`);if(!Number(i.hands||0)||Number(i.hands)<2)slots.push(`Оружие ${r} — левая рука`)}return slots}return slots}
function inventoryItemCard(i){const slots=compatibleSlots(i);return `<article class="bag-item" data-item-details="${i.inventory_id}">${itemVisual(i)}<div><b>${esc(i.name)}</b><small>${esc(i.category)} · ${esc(i.quality)}</small></div>${slots.length?`<select class="equipment-select" data-equip="${i.inventory_id}"><option value="">Экипировать…</option>${slots.map(s=>`<option>${esc(s)}</option>`).join('')}</select>`:''}</article>`}
function renderInventory(p,c){
 const cap=data.capacity,d=data.derived,a=d.attack,limits=data.equipmentLimits;
 const bySlot=Object.fromEntries(data.inventory.filter(i=>i.equipped_slot).map(i=>[i.equipped_slot,i]));
 const roman=['I','II','III','IV'][d.activeWeaponSet-1]||'I';
 const quick=Array.from({length:limits.quickSlots},(_,n)=>equipmentSlot(`Быстрый предмет ${n+1}`,String(n+1),`quick q${n+1}`,bySlot)).join('');
 const weaponSets=Array.from({length:4},(_,n)=>{const r=['I','II','III','IV'][n],unlocked=n<limits.weaponSets,item=bySlot[`Оружие ${r} — правая рука`];return `<button class="weapon-set ${n+1===d.activeWeaponSet?'active':''}" data-weapon-set="${n+1}" ${unlocked?'':'disabled'}><b>${r}</b>${unlocked?(item?itemVisual(item):'<span>◇</span>'):'<span>🔒</span>'}</button>`}).join('');
 const stats=[
  statIcon('health.png','Здоровье',`${c.health}/${c.health_max}`,'Текущее и максимальное здоровье.'),
  statIcon('accuracy.png','Точность',a.accuracy,`Навык атаки: ${a.skill}. Учитывает активный комплект и экипировку.`),
  statIcon('critical.png','Крит. шанс',`${a.criticalChance}%`,'Вероятность критического результата.'),
  statIcon('recovery.png','Восстановление',roundText(a.recovery),'Задержка от активного оружия и надетой брони.'),
  statIcon('damage.png','Урон',`${a.damageMin}–${a.damageMax}`,'Урон активного оружейного комплекта с учётом Силы.'),
  '<h3>Защиты</h3>',statIcon('endurance.png','Выносливость',d.defenses['Выносливость']||0),statIcon('will.png','Воля',d.defenses['Воля']||0),statIcon('magic.png','Магия',d.defenses['Магия']||0),statIcon('parry.png','Парирование',d.defenses['Парирование']||0),statIcon('dodge.png','Уклонение',d.defenses['Уклонение']||0),
  '<h3>Броня</h3>',statIcon('armor.png','Поглощение',d.armor||0),statIcon('deflection.png','Отражение',`${d.deflection||0}%`)
 ].join('');
 const portrait=c.portrait_url?`<img class="paperdoll-character" src="${esc(c.portrait_url)}" alt="${esc(c.name)}">`:`<div class="paperdoll-silhouette">${esc(c.name[0]||'Ж')}</div>`;
 const slots=[equipmentSlot('Голова','Голова','head',bySlot),equipmentSlot('Торс','Торс','torso',bySlot),equipmentSlot('Аксессуар 1','Аксессуар','accessory-one',bySlot),equipmentSlot('Руки','Руки','hands',bySlot),equipmentSlot('Ноги','Ноги','feet',bySlot),equipmentSlot('Аксессуар 2','Аксессуар','accessory-two',bySlot),equipmentSlot(`Оружие ${roman} — правая рука`,'П. рука','weapon-main',bySlot),equipmentSlot(`Оружие ${roman} — левая рука`,'Л. рука','weapon-off',bySlot)].join('');
 const bagItems=data.inventory.filter(i=>!i.equipped_slot);
 p.innerHTML=`<div class="inventory-screen"><aside class="combat-sheet"><h2>Показатели</h2>${stats}</aside><section class="paperdoll"><div class="paperdoll-frame">${portrait}${slots}<div class="quick-title">Быстрый доступ</div><div class="quick-slots">${quick}</div></div><h3>Комплекты оружия</h3><div class="weapon-sets">${weaponSets}</div></section><aside class="bag"><header><div><h2>Инвентарь</h2><p>Занято ${cap.used} из ${cap.capacity} · Атлетика ${cap.athletics}</p></div><span>${bagItems.length}</span></header><div class="bag-scroll">${bagItems.map(inventoryItemCard).join('')||'<p class="empty-bag">Сумка пуста.</p>'}</div></aside></div>`;
}
function openItemDetails(id){const i=data.inventory.find(x=>Number(x.inventory_id)===Number(id));if(!i)return;const props=Object.entries(i.properties||{}).map(([k,v])=>`<li><span>${esc(k)}</span><b>${esc(v)}</b></li>`).join('');$('#item-dialog-body').innerHTML=`<div class="item-dialog-head">${itemVisual(i)}<div><small>${esc(i.category)} · ${esc(i.quality)}</small><h2>${esc(i.name)}</h2>${i.equipped_slot?`<b>${esc(i.equipped_slot)}</b>`:''}</div></div><p>${esc(i.description||'Описание отсутствует.')}</p><ul>${i.damage_max?`<li><span>Урон</span><b>${i.damage_min}–${i.damage_max}</b></li>`:''}${i.armor?`<li><span>Броня</span><b>${i.armor}</b></li>`:''}${i.recovery?`<li><span>Восстановление</span><b>${roundText(i.recovery)}</b></li>`:''}${props}</ul><div class="item-dialog-actions">${i.equipped_slot?`<button class="action" data-unequip="${i.inventory_id}">СНЯТЬ</button>`:''}${i.source_url?`<a class="wiki-link" href="${esc(i.source_url)}" target="_blank" rel="noreferrer">ИСТОЧНИК ↗</a>`:''}</div>`;$('#item-dialog').showModal()}
async function mutate(path,body){try{const j=await request(`/api/portal/${encodeURIComponent(token)}/${path}`,{method:'POST',body:JSON.stringify(body)});data=normalize(j);toast(j.message);renderCabinet()}catch(e){toast(e.message)}}
document.addEventListener('click',e=>{
 const v=e.target.closest('[data-view]');if(v)showView(v.dataset.view);
 const card=e.target.closest('[data-id]');if(card)openRecord(card.dataset.id);
 const tabBtn=e.target.closest('[data-tab]');if(tabBtn){tab=tabBtn.dataset.tab;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===tabBtn));renderTab()}
 const selected=e.target.closest('[data-select-talent]');if(selected)selectTalent(selected.dataset.selectTalent);
 const details=e.target.closest('[data-talent-details]');if(details)openTalentDetails(details.dataset.talentDetails);
 const item=e.target.closest('[data-item-details]');if(item&&!e.target.closest('select'))openItemDetails(item.dataset.itemDetails);
 const set=e.target.closest('[data-weapon-set]');if(set&&!set.disabled)mutate('weapon-set',{number:+set.dataset.weaponSet});
 const trainingAction=e.target.closest('[data-training-kind]');if(trainingAction&&!trainingAction.disabled)trainingMutate('action',{kind:trainingAction.dataset.trainingKind,name:trainingAction.dataset.trainingName||''});
 const trainingSet=e.target.closest('[data-training-set]');if(trainingSet&&!trainingSet.disabled)trainingMutate('action',{kind:'weapon_set',number:+trainingSet.dataset.trainingSet});
 if(e.target.closest('.training-start'))trainingMutate('start');if(e.target.closest('.training-reset'))trainingMutate('reset');
 const scroll=e.target.closest('[data-scroll-talents]');if(scroll){const track=scroll.parentElement.querySelector('.talent-track');track?.scrollBy({left:Number(scroll.dataset.scrollTalents)*Math.max(340,track.clientWidth*.78),behavior:'smooth'})}
 const a=e.target.closest('[data-attr]');if(a)mutate('attribute',{name:a.dataset.attr});const t=e.target.closest('[data-talent]');if(t)mutate('talent',{name:t.dataset.talent});
 const u=e.target.closest('[data-unequip]');if(u){$('#item-dialog').close();mutate('equipment',{inventoryId:+u.dataset.unequip,unequip:true})}
 const sigil=e.target.closest('[data-sigil-key]');if(sigil){const s=spellSigil(sigil.dataset.sigilKey);if(s){selectedSigilKey=s.key;if(s.known){if(s.type==='core')spellSelection.core=s.key;else if(s.type==='expression')spellSelection.expression=s.key;else if(s.type==='enhancement')spellSelection.enhancement=spellSelection.enhancement===s.key?'':s.key;else{const wasSelected=spellSelection.accents.has(s.key);for(const key of [...spellSelection.accents])if(spellSigil(key)?.family===s.family)spellSelection.accents.delete(key);if(!wasSelected)spellSelection.accents.add(s.key)}}renderSpells($('#panel'),data.character)}}
 const learn=e.target.closest('[data-learn-sigil]');if(learn)mutate('sigil/learn',{inventoryId:+learn.dataset.learnSigil});
 if(e.target.closest('.sigil-reset')){spellSelection={core:'',expression:'',accents:new Set(),enhancement:''};selectedSigilKey='';renderSpells($('#panel'),data.character)}
 if(e.target.id==='save-spell'){const state=spellFormulaState(data.character);if(state.ready)mutate('spell',{name:$('#spell-name').value,core:spellSelection.core,expression:spellSelection.expression,accents:[...spellSelection.accents],enhancements:spellSelection.enhancement?[spellSelection.enhancement]:[]})}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-equip]')&&e.target.value)mutate('equipment',{inventoryId:+e.target.dataset.equip,slot:e.target.value})});$('#search').addEventListener('input',renderArchive);$('#record .close').onclick=()=>$('#record').close();$('#talent-dialog .close').onclick=()=>$('#talent-dialog').close();$('#item-dialog .close').onclick=()=>$('#item-dialog').close();boot();
