const q=new URLSearchParams(location.search),h=new URLSearchParams(location.hash.slice(1)),api=(q.get('api')||localStorage.getItem('tyranny_api')||'').replace(/\/$/,''),token=h.get('token')||q.get('token')||'';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let archive=[],data=null,tab='overview',selectedTalentName=''; if(api)localStorage.setItem('tyranny_api',api);
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3500)};
async function request(path,opt={}){const r=await fetch(api+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`Ошибка ${r.status}`);return j}
function normalize(j={}){return {...j,character:{attributes:{},skills:{},talents:[],...(j.character||{})},inventory:Array.isArray(j.inventory)?j.inventory:[],spells:Array.isArray(j.spells)?j.spells:[],talentLibrary:Array.isArray(j.talentLibrary)?j.talentLibrary:[],factionTalents:Array.isArray(j.factionTalents)?j.factionTalents:[],reputations:j.reputations||{},abilityDetails:j.abilityDetails||{},sigils:{cores:[],expressions:[],accents:[],enhancements:[],...(j.sigils||{})},equipmentSlots:Array.isArray(j.equipmentSlots)?j.equipmentSlots:[],equipmentLimits:{weaponSets:2,quickSlots:4,...(j.equipmentLimits||{})},attributeDetails:j.attributeDetails||{},skillAttributes:j.skillAttributes||{},derived:{defenses:{},attack:{accuracy:0,damageMin:1,damageMax:2,recovery:0,criticalChance:1,skill:'Безоружный бой'},armor:0,deflection:0,activeWeaponSet:1,cooldownMultiplier:1,cooldownPercent:0,equipmentRecovery:0,...(j.derived||{})},capacity:{used:0,capacity:0,athletics:0,...(j.capacity||{})}}}
function tip(name,text){return `<span class="tip" title="${esc(text)}">${esc(name)}</span>`}
async function boot(){if(!api){$('#loading').textContent='Адрес API не указан. Откройте ссылку из Discord.';return}try{const a=await request('/api/archive');archive=Array.isArray(a.characters)?a.characters:[];renderArchive();if(token){data=normalize(await request('/api/portal/'+encodeURIComponent(token)));$('#cabinet-nav').hidden=false;renderCabinet();showView('cabinet')}else showView('archive');$('#loading').hidden=true}catch(e){$('#loading').textContent=e.message}}
function showView(name){$('#archive-view').hidden=name!=='archive';$('#cabinet-view').hidden=name!=='cabinet';document.querySelectorAll('.topbar nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
function renderArchive(){const term=$('#search').value.toLowerCase(),rows=archive.filter(c=>[c.name,c.background,c.specialization_1,c.specialization_2].join(' ').toLowerCase().includes(term));$('#archive-count').textContent=`${rows.length} дел`;$('#archive-grid').innerHTML=rows.map(c=>`<button class="record-card" data-id="${c.id}" style="--portrait:${c.portrait_url?`url('${esc(c.portrait_url)}')`:'linear-gradient(135deg,#351016,#0b0b0d)'}"><div><span class="level">УРОВЕНЬ ${c.level}</span><h2>${esc(c.name)}</h2><p>${esc(c.background)}</p><p>${esc(c.specialization_1)} · ${esc(c.specialization_2)}</p></div></button>`).join('')||'<p>Персонажи не найдены.</p>'}
async function openRecord(id){try{const d=normalize(await request('/api/archive/'+id)),c=d.character;$('#record-body').innerHTML=`<small>ЛИЧНОЕ ДЕЛО · УРОВЕНЬ ${c.level}</small><h1>${esc(c.name)}</h1><p>${esc(c.background)} · ${esc(c.specialization_1)} / ${esc(c.specialization_2)}</p><div class="grid">${statsBox(c,d,false)}${skillsBox(c)}</div>`;$('#record').showModal()}catch(e){toast(e.message)}}
function renderCabinet(){const c=data.character;$('#profile-head').innerHTML=`${c.portrait_url?`<img class="portrait" src="${esc(c.portrait_url)}" alt="">`:''}<div><small>ЛИЧНОЕ ДЕЛО · УРОВЕНЬ ${c.level}</small><h1>${esc(c.name)}</h1><p>${esc(c.background)} · ${esc(c.specialization_1)} / ${esc(c.specialization_2)}</p><b>${c.health}/${c.health_max} здоровья · ${c.experience} опыта</b></div>`;renderTab()}
function statsBox(c,d,editable=true){const details=d.attributeDetails||{};return `<section class="box"><h2>Характеристики</h2>${Object.entries(c.attributes).map(([n,v])=>{const cost=1+Math.floor(Math.max(0,v-9)/10);return `<div class="stat"><div>${tip(n,details[n]?.description||'Базовая характеристика персонажа.')}<small>${esc(details[n]?.effects||'')}</small></div><b class="value">${v}</b>${editable?`<button class="plus" data-attr="${esc(n)}" ${c.attribute_points<cost?'disabled':''}>+${cost}</button>`:''}</div>`}).join('')}${editable?`<p>Свободно: <b>${c.attribute_points}</b></p>`:''}</section>`}
function skillsBox(c){return `<section class="box"><h2>Навыки</h2>${Object.entries(c.skills).sort((a,b)=>b[1].value-a[1].value).map(([n,v])=>`<div class="stat"><div>${tip(n,`База: ${data?.skillAttributes?.[n]?.join(' × 1,5 / × 0,5')||'определяется характеристиками'}; растёт при применении.`)}<div class="meter"><i style="width:${Math.min(100,v.experience%100)}%"></i></div></div><b class="value">${v.value}</b><span>${v.experience} XP</span></div>`).join('')}</section>`}
function abilitiesBox(c){const details=data?.abilityDetails||{},rows=(c?.talents||[]).filter(t=>details[t.name]);if(!rows.length)return'';return `<section class="box"><h2>Способности</h2>${rows.map(t=>{const a=details[t.name]||{},base=parseFloat(a.cooldown),effective=Number.isFinite(base)?(base*(data?.derived?.cooldownMultiplier??1)).toFixed(1)+' сек.':(a.cooldown||'не указана');return `<article class="item">${a.icon?`<img src="${esc(a.icon)}" alt="">`:''}<div><h3>${tip(t.name,a.description||t.description||'')}</h3><p>${esc(a.type||'Способность')} · перезарядка ${effective} (база ${esc(a.cooldown||'не указана')})</p><p>${esc(Array.isArray(a.effects)?a.effects.join(' · '):'')}</p></div></article>`}).join('')}</section>`}
function renderTab(){const c=data.character,p=$('#panel');if(tab==='overview')p.innerHTML=`<div class="grid">${statsBox(c,data)}<section class="box"><h2>Производные значения</h2>${Object.entries(data.derived.defenses).map(([n,v])=>`<div class="stat"><span>${tip(n,'Защита от соответствующего типа атак; рассчитывается из характеристик, навыков, предметов и эффектов.')}</span><b class="value">${v}</b></div>`).join('')}<div class="stat"><span>${tip('Перезарядка','Быстрота изменяет восстановление способностей на 3% за пункт относительно 10.')}</span><b>${data.derived.cooldownPercent>=0?'−':'+'}${Math.abs(data.derived.cooldownPercent)}%</b></div><div class="stat"><span>Восстановление экипировки</span><b>${data.derived.equipmentRecovery} сек.</b></div></section>${abilitiesBox(c)}${skillsBox(c)}</div>`;
 else if(tab==='development')p.innerHTML=`<div class="grid">${statsBox(c,data)}${skillsBox(c)}<section class="box"><h2>Как растёт персонаж</h2><p>За уровень вы получаете одно очко характеристики и одно очко таланта. Навыки в Tyranny растут от успешного применения в бою и диалогах — их нельзя купить очками уровня.</p></section></div>`;
 else if(tab==='talents')renderTalents(p,c);else if(tab==='factions')renderFactions(p,c);else if(tab==='spells')renderSpells(p,c);else renderInventory(p,c)}
function localTalentIcon(url){if(!url)return'';try{const parts=decodeURIComponent(new URL(url,location.href).pathname).split('/'),revision=parts.indexOf('revision'),filename=parts[revision>0?revision-1:parts.length-1].replace(/[\s_]+/g,'_');return `assets/talent-icons/${encodeURIComponent(filename)}`}catch{return url}}
function talentIcon(t,kind=''){const letter=(t.name||'?').trim()[0]||'?';return `<span class="talent-game-icon ${kind}"><span class="talent-fallback">${esc(letter)}</span>${t.icon_url?`<img src="${esc(localTalentIcon(t.icon_url))}" alt="" loading="lazy" onerror="this.remove()">`:''}</span>`}
function talentInfo(name,c=data?.character){const talent=(data?.talentLibrary||[]).find(t=>t.name===name);if(!talent)return null;const owned=new Set((c?.talents||[]).map(x=>x.name)),automatic=Number(talent.automatic_level||0),has=owned.has(talent.name)||(automatic>0&&c.level>=automatic),spent=(c?.talents||[]).filter(x=>x.tree_name===talent.tree||x.tree===talent.tree).length,needed=Math.max(0,Number(talent.tier||0)-spent);return {talent,automatic,has,spent,needed,canBuy:!has&&!automatic&&needed===0&&Number(c?.talent_points||0)>0}}
function talentSelection(name,c){const s=talentInfo(name,c);if(!s)return '<section id="talent-selection" class="talent-selection"><p>Выберите талант в одном из деревьев.</p></section>';const t=s.talent,requirement=s.has?'Талант изучен':s.automatic?`Открывается автоматически на ${s.automatic} уровне`:s.needed?`Нужно ещё вложить в ветку: ${s.needed}`:'Доступен для изучения';return `<section id="talent-selection" class="talent-selection">${talentIcon(t,'large')}<div><small>${esc(t.tree)} · ступень ${t.tier}</small><h2>${esc(t.name)}</h2><b class="talent-requirement ${s.canBuy?'ready':''}">${esc(requirement)}</b><p>${esc(t.description)}</p></div><div class="talent-actions"><button class="talent-more" data-talent-details="${esc(t.name)}">ПОДРОБНОСТИ</button>${s.canBuy?`<button class="action" data-talent="${esc(t.name)}">ИЗУЧИТЬ</button>`:''}</div></section>`}
function renderTalents(p,c){const trees={};(data?.talentLibrary||[]).forEach(t=>(trees[t.tree]??=[]).push(t));const entries=Object.entries(trees);if(!entries.length){p.innerHTML='<section class="box"><p>Справочник талантов временно недоступен. Ваше личное дело продолжает работать.</p></section>';return}if(!entries.some(([,ts])=>ts.some(t=>t.name===selectedTalentName)))selectedTalentName=entries[0][1][0]?.name||'';p.innerHTML=`<div class="talent-heading"><p>Свободные очки талантов: <b>${c.talent_points??0}</b><small>Базовые деревья Вершителя и личные ветки предыстории используют общий запас.</small></p></div><div class="talent-carousel"><button class="talent-arrow prev" data-scroll-talents="-1" aria-label="Предыдущие ветки">‹</button><div class="talent-track">${entries.map(([tree,ts])=>{const spent=(c.talents||[]).filter(x=>x.tree_name===tree||x.tree===tree).length,tiers=[...new Set(ts.map(t=>Number(t.tier||0)))].sort((a,b)=>a-b);return `<section class="talent-tree"><header><h2>${esc(tree)}</h2><b>${spent}</b></header><div class="talent-lanes">${tiers.map(tier=>`<div class="talent-tier"><span>${tier}</span><div>${ts.filter(t=>Number(t.tier||0)===tier).map(t=>{const s=talentInfo(t.name,c),state=s.has?'owned':s.canBuy?'available':'locked';return `<button class="talent-node ${state} ${t.name===selectedTalentName?'selected':''}" data-select-talent="${esc(t.name)}" title="${esc(t.name)}">${talentIcon(t)}</button>`}).join('')}</div></div>`).join('')}</div></section>`}).join('')}</div><button class="talent-arrow next" data-scroll-talents="1" aria-label="Следующие ветки">›</button></div>${talentSelection(selectedTalentName,c)}`}
function selectTalent(name){selectedTalentName=name;document.querySelectorAll('.talent-node').forEach(n=>n.classList.toggle('selected',n.dataset.selectTalent===name));const old=$('#talent-selection');if(old)old.outerHTML=talentSelection(name,data.character)}
function openTalentDetails(name){const s=talentInfo(name),t=s?.talent;if(!t)return;const requirement=s.has?'Изучен':s.automatic?`Автоматически открывается на ${s.automatic} уровне`:`Требуется ${t.tier} очк. в ветке; вложено ${s.spent}`;$('#talent-dialog-body').innerHTML=`<div class="talent-dialog-head">${talentIcon(t,'large')}<div><small>${esc(t.tree)}</small><h2>${esc(t.name)}</h2>${t.name_en?`<i>${esc(t.name_en)}</i>`:''}</div></div><div class="talent-divider"></div><p class="talent-dialog-requirement">ТРЕБОВАНИЯ: <b>${esc(requirement)}</b></p><p class="talent-dialog-description">${esc(t.description)}</p>${t.source_url?`<a class="wiki-link" href="${esc(t.source_url)}" target="_blank" rel="noreferrer">ОТКРЫТЬ ИСТОЧНИК В TYRANNY WIKI ↗</a>`:''}`;$('#talent-dialog').showModal()}
function renderFactions(p,c){const factions=new Set([...Object.keys(data.reputations),...data.factionTalents.map(t=>t.faction)]);p.innerHTML=`<div class="talent-trees">${[...factions].sort().map(name=>{const rep=data.reputations[name]||{favor:0,wrath:0},favorTier=Math.min(5,Math.floor(rep.favor/20)),wrathTier=Math.min(5,Math.floor(rep.wrath/20)),talents=data.factionTalents.filter(t=>t.faction===name);return `<section class="box"><h2>${esc(name)}</h2><div class="rep-axis"><b>Благосклонность ${rep.favor}/100 · ранг ${favorTier}</b><div class="meter"><i style="width:${rep.favor}%"></i></div></div><div class="rep-axis wrath"><b>Гнев ${rep.wrath}/100 · ранг ${wrathTier}</b><div class="meter"><i style="width:${rep.wrath}%"></i></div></div>${talents.map(t=>{const rank=t.axis==='favor'?favorTier:wrathTier,has=rank>=t.tier;return `<article class="talent ${has?'owned':''}">${talentIcon(t)}<div><b>${tip(t.name,`${t.name_en}. ${t.description}`)}</b><p>${esc(t.description)}</p><small>${t.axis==='favor'?'Благосклонность':'Гнев'} · ранг ${t.tier}</small></div><b>${has?'✓':'🔒'}</b></article>`}).join('')||'<p>У этой стороны нет отдельных фракционных талантов.</p>'}</section>`}).join('')}</div>`}
function options(rows){return rows.map(x=>`<option>${esc(x)}</option>`).join('')}
function renderSpells(p,c){p.innerHTML=`<section class="box"><h2>Создать заклинание</h2><div class="spell-form"><label>Название<input id="spell-name"></label><label>Основа<select id="spell-core">${options(data.sigils.cores)}</select></label><label>Выражение<select id="spell-expression">${options(data.sigils.expressions)}</select></label><label>Акцент<select id="spell-accent"><option value="">Нет</option>${options(data.sigils.accents)}</select></label><label>Усиление<select id="spell-enhancement"><option value="">Нет</option>${options(data.sigils.enhancements)}</select></label><label>Сложность<input id="spell-difficulty" type="number" min="0" value="0"></label></div><p>Доступные Знания: <b>${c.skills?.['Знания']?.value??0}</b>. Сложность не может их превышать.</p><button id="save-spell" class="action">ЗАПИСАТЬ ФОРМУЛУ</button></section><section class="box"><h2>Гримуар</h2>${data.spells.map(s=>`<article class="spell-card"><h3>${esc(s.name)} <small>· ${s.difficulty}</small></h3><p>${esc(s.core)} + ${esc(s.expression)}${[...(s.accents||[]),...(s.enhancements||[])].length?' + '+esc([...(s.accents||[]),...(s.enhancements||[])].join(', ')):''}</p></article>`).join('')||'<p>Заклинаний пока нет.</p>'}</section>`}
function itemVisual(i){const letter=(i?.name||'?')[0]||'?';return `<span class="gear-art"><i>${esc(letter)}</i>${i?.image_url?`<img src="${esc(i.image_url)}" alt="" referrerpolicy="no-referrer" loading="lazy" onerror="this.remove()">`:''}</span>`}
function equipmentSlot(slot,label,position,bySlot){const item=bySlot[slot];return `<div class="paper-slot ${position}"><b>${esc(label)}</b><button ${item?`data-item-details="${item.inventory_id}"`:''} title="${esc(item?.name||slot)}">${item?itemVisual(item):'<span class="empty-rune">◇</span>'}</button></div>`}
function statIcon(file,label,value,help=''){return `<div class="combat-stat" title="${esc(help||label)}"><img src="assets/stat-icons/${file}" alt=""><span>${esc(label)}</span><b>${esc(value)}</b></div>`}
function compatibleSlots(i){const limits=data.equipmentLimits,slots=[];if(i.category==='Броня')return i.slot?[i.slot]:['Голова','Торс','Руки','Ноги'];if(i.category==='Аксессуары')return['Аксессуар 1','Аксессуар 2'];if(['Расходуемые предметы','Зелья','Еда'].includes(i.category))return Array.from({length:limits.quickSlots},(_,n)=>`Быстрый предмет ${n+1}`);if(['Одноручное оружие','Двуручное оружие','Парное оружие','Луки','Метательное оружие','Посохи','Щиты'].includes(i.category)){for(let n=1;n<=limits.weaponSets;n++){const r=['I','II','III','IV'][n-1];if(i.category!=='Щиты')slots.push(`Оружие ${r} — правая рука`);if(!Number(i.hands||0)||Number(i.hands)<2)slots.push(`Оружие ${r} — левая рука`)}return slots}return slots}
function inventoryItemCard(i){const slots=compatibleSlots(i);return `<article class="bag-item" data-item-details="${i.inventory_id}">${itemVisual(i)}<div><b>${esc(i.name)}</b><small>${esc(i.category)} · ${esc(i.quality)}</small></div>${slots.length?`<select class="equipment-select" data-equip="${i.inventory_id}"><option value="">Экипировать…</option>${slots.map(s=>`<option>${esc(s)}</option>`).join('')}</select>`:''}</article>`}
function renderInventory(p,c){
 const cap=data.capacity,d=data.derived,a=d.attack,limits=data.equipmentLimits;
 const bySlot=Object.fromEntries(data.inventory.filter(i=>i.equipped_slot).map(i=>[i.equipped_slot,i]));
 const roman=['I','II','III','IV'][d.activeWeaponSet-1]||'I';
 const quick=Array.from({length:limits.quickSlots},(_,n)=>equipmentSlot(`Быстрый предмет ${n+1}`,String(n+1),`quick q${n+1}`,bySlot)).join('');
 const weaponSets=Array.from({length:4},(_,n)=>{const r=['I','II','III','IV'][n],unlocked=n<limits.weaponSets,item=bySlot[`Оружие ${r} — правая рука`];return `<button class="weapon-set ${n+1===d.activeWeaponSet?'active':''}" data-weapon-set="${n+1}" ${unlocked?'':'disabled'}><b>${r}</b>${unlocked?(item?itemVisual(item):'<span>◇</span>'):'<span>🔒</span>'}</button>`}).join('');
 const stats=[
  statIcon('health.png','Здоровье',`${c.health}/${c.health_max}`,'Текущее и максимальное здоровье.'),
  statIcon('accuracy.png','Точность',a.accuracy,`Навык атаки: ${a.skill}. Учитывает активный комплект и экипировку.`),
  statIcon('critical.png','Крит. шанс',`${a.criticalChance}%`,'Вероятность критического результата.'),
  statIcon('recovery.png','Восстановление',`${a.recovery} сек.`,'Задержка от активного оружия и надетой брони.'),
  statIcon('damage.png','Урон',`${a.damageMin}–${a.damageMax}`,'Урон активного оружейного комплекта с учётом Силы.'),
  '<h3>Защиты</h3>',statIcon('endurance.png','Выносливость',d.defenses['Выносливость']||0),statIcon('will.png','Воля',d.defenses['Воля']||0),statIcon('magic.png','Магия',d.defenses['Магия']||0),statIcon('parry.png','Парирование',d.defenses['Парирование']||0),statIcon('dodge.png','Уклонение',d.defenses['Уклонение']||0),
  '<h3>Броня</h3>',statIcon('armor.png','Поглощение',d.armor||0),statIcon('deflection.png','Отражение',`${d.deflection||0}%`)
 ].join('');
 const portrait=c.portrait_url?`<img class="paperdoll-character" src="${esc(c.portrait_url)}" alt="${esc(c.name)}">`:`<div class="paperdoll-silhouette">${esc(c.name[0]||'Ж')}</div>`;
 const slots=[equipmentSlot('Голова','Голова','head',bySlot),equipmentSlot('Торс','Торс','torso',bySlot),equipmentSlot('Аксессуар 1','Аксессуар','accessory-one',bySlot),equipmentSlot('Руки','Руки','hands',bySlot),equipmentSlot('Ноги','Ноги','feet',bySlot),equipmentSlot('Аксессуар 2','Аксессуар','accessory-two',bySlot),equipmentSlot(`Оружие ${roman} — правая рука`,'П. рука','weapon-main',bySlot),equipmentSlot(`Оружие ${roman} — левая рука`,'Л. рука','weapon-off',bySlot)].join('');
 const bagItems=data.inventory.filter(i=>!i.equipped_slot);
 p.innerHTML=`<div class="inventory-screen"><aside class="combat-sheet"><h2>Показатели</h2>${stats}</aside><section class="paperdoll"><div class="paperdoll-frame">${portrait}${slots}<div class="quick-title">Быстрый доступ</div><div class="quick-slots">${quick}</div></div><h3>Комплекты оружия</h3><div class="weapon-sets">${weaponSets}</div></section><aside class="bag"><header><div><h2>Инвентарь</h2><p>Занято ${cap.used} из ${cap.capacity} · Атлетика ${cap.athletics}</p></div><span>${bagItems.length}</span></header><div class="bag-scroll">${bagItems.map(inventoryItemCard).join('')||'<p class="empty-bag">Сумка пуста.</p>'}</div></aside></div>`;
}
function openItemDetails(id){const i=data.inventory.find(x=>Number(x.inventory_id)===Number(id));if(!i)return;const props=Object.entries(i.properties||{}).map(([k,v])=>`<li><span>${esc(k)}</span><b>${esc(v)}</b></li>`).join('');$('#item-dialog-body').innerHTML=`<div class="item-dialog-head">${itemVisual(i)}<div><small>${esc(i.category)} · ${esc(i.quality)}</small><h2>${esc(i.name)}</h2>${i.equipped_slot?`<b>${esc(i.equipped_slot)}</b>`:''}</div></div><p>${esc(i.description||'Описание отсутствует.')}</p><ul>${i.damage_max?`<li><span>Урон</span><b>${i.damage_min}–${i.damage_max}</b></li>`:''}${i.armor?`<li><span>Броня</span><b>${i.armor}</b></li>`:''}${i.recovery?`<li><span>Восстановление</span><b>${i.recovery} сек.</b></li>`:''}${props}</ul><div class="item-dialog-actions">${i.equipped_slot?`<button class="action" data-unequip="${i.inventory_id}">СНЯТЬ</button>`:''}${i.source_url?`<a class="wiki-link" href="${esc(i.source_url)}" target="_blank" rel="noreferrer">TYRANNY WIKI ↗</a>`:''}</div>`;$('#item-dialog').showModal()}
async function mutate(path,body){try{const j=await request(`/api/portal/${encodeURIComponent(token)}/${path}`,{method:'POST',body:JSON.stringify(body)});data=normalize(j);toast(j.message);renderCabinet()}catch(e){toast(e.message)}}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v)showView(v.dataset.view);const card=e.target.closest('[data-id]');if(card)openRecord(card.dataset.id);const tabBtn=e.target.closest('[data-tab]');if(tabBtn){tab=tabBtn.dataset.tab;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===tabBtn));renderTab()}const selected=e.target.closest('[data-select-talent]');if(selected)selectTalent(selected.dataset.selectTalent);const details=e.target.closest('[data-talent-details]');if(details)openTalentDetails(details.dataset.talentDetails);const item=e.target.closest('[data-item-details]');if(item&&!e.target.closest('select'))openItemDetails(item.dataset.itemDetails);const set=e.target.closest('[data-weapon-set]');if(set&&!set.disabled)mutate('weapon-set',{number:+set.dataset.weaponSet});const scroll=e.target.closest('[data-scroll-talents]');if(scroll){const track=scroll.parentElement.querySelector('.talent-track');track?.scrollBy({left:Number(scroll.dataset.scrollTalents)*Math.max(340,track.clientWidth*.78),behavior:'smooth'})}const a=e.target.closest('[data-attr]');if(a)mutate('attribute',{name:a.dataset.attr});const t=e.target.closest('[data-talent]');if(t)mutate('talent',{name:t.dataset.talent});const u=e.target.closest('[data-unequip]');if(u){$('#item-dialog').close();mutate('equipment',{inventoryId:+u.dataset.unequip,unequip:true})}if(e.target.id==='save-spell')mutate('spell',{name:$('#spell-name').value,core:$('#spell-core').value,expression:$('#spell-expression').value,accents:[$('#spell-accent').value].filter(Boolean),enhancements:[$('#spell-enhancement').value].filter(Boolean),difficulty:+$('#spell-difficulty').value})});
document.addEventListener('change',e=>{if(e.target.matches('[data-equip]')&&e.target.value)mutate('equipment',{inventoryId:+e.target.dataset.equip,slot:e.target.value})});$('#search').addEventListener('input',renderArchive);$('#record .close').onclick=()=>$('#record').close();$('#talent-dialog .close').onclick=()=>$('#talent-dialog').close();$('#item-dialog .close').onclick=()=>$('#item-dialog').close();boot();
