async function loadTraining(){if(trainingLoading)return;trainingLoading=true;try{const j=await request(`/api/portal/${encodeURIComponent(token)}/training`);training=j.training||{active:false}}catch(e){toast(e.message);training={active:false}}finally{trainingLoading=false;if(tab==='training')renderTraining($('#panel'),data.character)}}
function hpBar(current,max){const percent=Math.max(0,Math.min(100,Number(current||0)/Math.max(1,Number(max||1))*100));return `<div class="fight-hp"><i style="width:${percent}%"></i><b>${current} / ${max}</b></div>`}
function combatActionIcon(x){if(x.icon)return `<img src="${esc(localTalentIcon(x.icon))}" alt="">`;if(x.kind==='spell'){const spell=(data?.spells||[]).find(s=>s.name===x.name);if(spell)return spellCoreIcon(spell,'combat')}return `<span>${x.kind==='attack'?'⚔':x.kind==='disengage'?'↶':'◆'}</span>`}
function combatActionButton(x,extra=''){const assigning=extra.includes('data-picker-action')&&quickbarEditing,disabled=!assigning&&(x.remaining||x.disabledReason||training?.finished),effect=(x.cells||[]).map(cell=>`${cell.x}:${cell.y}`).join(',');return `<button class="training-action ${x.kind}" draggable="true" data-action-kind="${esc(x.kind)}" data-action-name="${esc(x.name)}" data-training-kind="${esc(x.kind)}" data-training-name="${esc(x.name)}" data-effect-cells="${effect}" data-targeting="${esc(x.targeting||'unit')}" ${disabled?'disabled':''} title="${esc(x.disabledReason||x.description||'')}" ${extra}>${combatActionIcon(x)}<div><b>${esc(x.name)}</b><small>${esc(x.description||'')}</small><em>${x.remaining?`Готово через ${x.remaining} раунд.`:x.disabledReason||`Дальность: ${x.range??0} м${x.area?` · область ${x.area} м`:''}`}</em></div></button>`}
function quickbarAssignments(){return new Map((data?.combatQuickbar||[]).map(x=>[Number(x.slot),x]))}
function quickbarAction(slot,actions){const savedRows=data?.combatQuickbar||[],saved=quickbarAssignments().get(slot);if(saved)return actions.find(x=>x.kind===saved.action_kind&&x.name===saved.action_name);const defaults=actions.filter(x=>['attack','ability','spell'].includes(x.kind));return savedRows.length?null:defaults[slot-1]||null}
function quickbarSlot(slot,actions){const x=quickbarAction(slot,actions),disabled=!x||x.remaining||x.disabledReason||training?.finished;return `<button class="combat-quick-slot ${x?'filled':'empty'} ${quickbarEditing===slot?'editing':''}" data-quick-slot="${slot}" ${x?`data-training-kind="${esc(x.kind)}" data-training-name="${esc(x.name)}" data-effect-cells="${(x.cells||[]).map(c=>`${c.x}:${c.y}`).join(',')}" data-targeting="${esc(x.targeting||'unit')}"`:''} ${disabled&&x?'disabled':''} title="${esc(x?.disabledReason||x?.description||'Нажмите, чтобы назначить действие')}"><kbd>${slot}</kbd>${x?combatActionIcon(x):'<span>+</span>'}${x?.remaining?`<i>${x.remaining}</i>`:''}<em>${x?esc(x.name):'Пусто'}</em></button>`}
function combatPickerPanel(t){if(!combatPicker)return'';const source=combatPicker==='spell'?(t.actions||[]).filter(x=>x.kind==='spell'):combatPicker==='stance'?(t.stances||[]):(t.actions||[]);if(combatPicker==='stance')return `<div class="combat-picker stance-picker"><header><b>СТОЙКИ</b><button data-combat-picker-close>×</button></header>${source.length?source.map(x=>`<button data-stance-name="${esc(x.name)}" class="stance-choice ${t.activeStance===x.name?'active':''}">${combatActionIcon({...x,kind:'ability'})}<span><b>${esc(x.name.replace(/^Стойка:\s*/,''))}</b><small>${esc(x.description||'')}</small></span></button>`).join(''):'<p>Персонаж ещё не изучил ни одной стойки.</p>'}</div>`;return `<div class="combat-picker"><header><b>${combatPicker==='spell'?'ГРИМУАР':'НАЗНАЧЕНИЕ БЫСТРЫХ ДЕЙСТВИЙ'}</b><button data-combat-picker-close>×</button></header><p>${quickbarEditing?`Выберите действие для ячейки ${quickbarEditing} или перетащите его на нужную кнопку.`:'Перетащите действие на ячейку 1–9. Нажатие включает прицеливание.'}</p><div class="combat-picker-list">${source.map(x=>combatActionButton(x,'data-picker-action="1"')).join('')||'<small>Нет доступных действий.</small>'}</div></div>`}
function renderTraining(p,c){
 if(training===null){p.innerHTML='<section class="training-intro"><div class="training-rune">⚔</div><h2>Подготавливаем тренировочную арену…</h2></section>';loadTraining();return}
 if(!training.active){p.innerHTML=`<section class="training-intro"><p>Выводит токен персонажа на арену с манекенами, где можно зарамсится и посмотреть че делают кнопки.</p><button class="action training-start">НАЧАТЬ ТРЕНИРОВКУ</button></section>`;return}
 const t=training,d=t.derived||{},a=d.attack||{},dummy=t.dummy||{},summary=t.summary||{},grid=t.grid||{},turn=t.turn||{};
 const reachable=new Map((grid.reachable||[]).map(x=>[`${x.x}:${x.y}`,x.cost])),blocked=new Set((grid.blocked||[]).map(x=>`${x.x}:${x.y}`)),controlled=new Set((grid.controlZones||[]).map(x=>`${x.x}:${x.y}`)),tokens=new Map((grid.tokens||[]).map(x=>[`${x.x}:${x.y}`,x]));
 const cells=Array.from({length:(grid.width||1)*(grid.height||1)},(_,index)=>{const x=index%(grid.width||1),y=Math.floor(index/(grid.width||1)),key=`${x}:${y}`,cost=reachable.get(key),token=tokens.get(key),isBlocked=blocked.has(key),target=token?.team==='enemy';const interaction=target&&!t.finished?`data-target-id="${esc(token.id)}" title="Выбрать цель: ${esc(token.name)}"`:cost&&!t.finished?`data-move-x="${x}" data-move-y="${y}" title="Переместиться: ${cost} м"`:'disabled';return `<button class="tactical-cell ${cost?'reachable':''} ${controlled.has(key)?'controlled':''} ${isBlocked?'blocked':''}" data-cell="${key}" style="--x:${x+1};--y:${y+1}" ${interaction}>${cost?`<i>${cost}</i>`:''}${token?`<span class="combat-token ${token.team} ${token.selected?'selected':''} ${token.active?'active':''}" title="${esc(token.name)}">${token.portraitUrl?`<img src="${esc(token.portraitUrl)}" alt="">`:`<b>${token.team==='enemy'?'♟':esc((token.name||'?')[0])}</b>`}<em>${token.health}/${token.healthMax}</em></span>`:''}</button>`}).join('');
 const availableActions=t.actions||[],actions=availableActions.map(x=>combatActionButton(x)).join('');
 const sets=Array.from({length:t.character?.weaponSets||1},(_,i)=>`<button class="training-set ${i+1===t.character.activeWeaponSet?'active':''}" data-training-set="${i+1}" ${t.finished?'disabled':''}>${['I','II','III','IV'][i]}</button>`).join('');
 const initiative=(t.initiative||[]).map((x,i)=>`<div class="initiative-entry ${i===0?'first':''}"><b>${i+1}</b><span>${esc(x.name)}</span><em>d20: ${x.roll} ${x.bonus>=0?'+':''}${x.bonus} = ${x.total}</em></div>`).join('');
 const player=(grid.tokens||[]).find(x=>x.team==='player')||{x:0,y:0},target=(grid.tokens||[]).find(x=>x.selected)||{x:0,y:0};
 const trajectory=`<svg class="spell-trajectory" viewBox="0 0 ${grid.width} ${grid.height}" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="spell-arrow" markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5 Z"/></marker></defs><line x1="${player.x+.5}" y1="${player.y+.5}" x2="${target.x+.5}" y2="${target.y+.5}" marker-end="url(#spell-arrow)"/></svg>`;
 const portrait=t.character?.portraitUrl?`<img src="${esc(t.character.portraitUrl)}" alt="">`:`<span>${esc((t.character?.name||'?')[0])}</span>`;
 const attack=availableActions.find(x=>x.kind==='attack'),quickbar=Array.from({length:9},(_,i)=>quickbarSlot(i+1,availableActions)).join('');
 p.innerHTML=`<section class="training-screen combat-game-screen"><header class="training-header"><div><h2>Раунд ${t.round}</h2></div><div class="turn-resources"><b>${turn.movementRemaining}/${turn.movementMax} м</b><span>${turn.actionAvailable?'ДЕЙСТВИЕ ГОТОВО':'ДЕЙСТВИЕ ПОТРАЧЕНО'}</span></div><button class="training-reset">ЗАВЕРШИТЬ</button></header><div class="combat-arena"><section class="tactical-map-wrap"><div class="tactical-map" style="--cols:${grid.width};--rows:${grid.height};--battle-map:url('${esc(grid.image||'')}')">${cells}${trajectory}<aside class="tyranny-combat-hud"><div class="hud-top"><div class="hud-portrait">${portrait}<i>${c.level||1}</i></div><div class="hud-name"><b>${esc(t.character?.name||c.name)}</b>${hpBar(t.character?.health||c.health,t.character?.healthMax||c.health_max)}<small>${turn.movementRemaining} м движения · ${turn.actionAvailable?'действие готово':'действие потрачено'}</small></div></div><div class="hud-quickbar">${quickbar}</div><div class="hud-system-row"><button class="hud-round" data-training-kind="end_turn" title="Завершить ход">⌛</button><button class="hud-attack" ${attack?.disabledReason||t.finished?'disabled':''} data-training-kind="attack" data-training-name="Обычная атака" data-effect-cells="${(attack?.cells||[]).map(c=>`${c.x}:${c.y}`).join(',')}" title="Обычная атака">⚔</button><button data-combat-picker="ability" title="Умения и назначение быстрых кнопок">✦</button><button data-combat-picker="spell" title="Заклинания">◇</button><button class="${t.activeStance?'active':''}" data-combat-picker="stance" title="Стойки">♟</button><button data-combat-picker="initiative" title="Инициатива и журнал">☷</button></div><div class="hud-sets"><span>КОМПЛЕКТ</span>${sets}</div></aside>${combatPickerPanel(t)}<aside class="combat-info-drawer ${combatPicker==='initiative'?'open':''}"><header><b>БОЙ</b><button data-combat-picker-close>×</button></header><h3>Инициатива</h3>${initiative}<div class="range-readout"><small>ДИСТАНЦИЯ ДО ЦЕЛИ</small><b>${turn.distanceToTarget} м</b></div><h3>${esc(dummy.name||'Манекен')}</h3>${hpBar(dummy.health,dummy.healthMax)}<p>Броня ${dummy.armor||0} · укрытие ${esc(turn.cover||'нет')}</p><ol>${(t.log||[]).slice(0,8).map(line=>`<li>${esc(line)}</li>`).join('')}</ol></aside></div><footer><span>${esc(grid.name||'Поле боя')}</span></footer></section></div><div class="combat-mobile-actions"><h3>Все действия</h3>${actions}</div></section>`;
}
async function trainingMutate(path,body={}){try{const j=await request(`/api/portal/${encodeURIComponent(token)}/training/${path}`,{method:'POST',body:JSON.stringify(body)});training=j.training||{active:false};toast(j.message);if(tab==='training')renderTraining($('#panel'),data.character)}catch(e){toast(e.message)}}
function localTalentIcon(url){if(!url)return'';if(url.startsWith('assets/'))return url;try{const parts=decodeURIComponent(new URL(url,location.href).pathname).split('/'),revision=parts.indexOf('revision'),filename=parts[revision>0?revision-1:parts.length-1].replace(/[\s_]+/g,'_');return `assets/talent-icons/${encodeURIComponent(filename)}`}catch{return url}}
function sigilIcon(s,size=''){return `<span class="sigil-icon ${size}"><img src="${esc(s?.image_url||'assets/game-combat/icon_option_inventory.png')}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src='assets/game-combat/icon_option_inventory.png'"></span>`}
function statIcon(file,label,value,help=''){return `<div class="combat-stat" title="${esc(help||label)}"><img src="assets/stat-icons/${file}" alt=""><span>${esc(label)}</span><b>${esc(value)}</b></div>`}
