let playerShop=null,shopPending=false,playerShopKey='consumables',playerShopCategory='',playerShopQuality='',playerShopQuery='';
function moneyText(w={}){return `${w.iron||0} железных · ${w.bronze||0} бронзовых · ${w.copper||0} медных колец`}
const originalPlayerRenderCabinet=renderCabinet;
renderCabinet=function(){originalPlayerRenderCabinet();$('#profile-head').insertAdjacentHTML('beforeend',`<div class="wallet-line">${moneyText(data.wallet)}<button data-tab="shop">МАГАЗИНЫ</button></div>`)};
const originalPlayerRenderTab=renderTab;
renderTab=function(){if(tab==='shop'){renderPlayerShop();return}originalPlayerRenderTab()};
function playerShopURL(){return `/api/portal/${encodeURIComponent(token)}/shop?${new URLSearchParams({shopKey:playerShopKey,category:playerShopCategory,quality:playerShopQuality,q:playerShopQuery})}`}
async function loadPlayerShop(){try{playerShop=await request(playerShopURL());if(tab==='shop')renderPlayerShop()}catch(error){toast(error.message)}}
function renderPlayerShop(){const panel=$('#panel');if(!playerShop){panel.innerHTML='<section class="box"><h2>Открываем магазин…</h2></section>';loadPlayerShop();return}panel.innerHTML=`<header class="box"><nav class="merchant-nav">${playerShop.shops.map(s=>`<button class="${s.key===playerShopKey?'active':''}" data-player-merchant="${s.key}">${esc(s.name)}</button>`).join('')}</nav><h2>${esc(playerShop.settings.name)}</h2><div class="wallet-line">${moneyText(playerShop.wallet)}</div><p>100 медных = 1 бронзовое · 100 бронзовых = 1 железное. Цены в медных кольцах. Запас лавки общий для игроков сервера.</p>${playerShop.settings.enabled?'':'<p>Магазин закрыт мастером.</p>'}<div class="merchant-filters"><input id="player-shop-search" value="${esc(playerShopQuery)}" placeholder="Поиск товара"><select id="player-shop-category" aria-label="Категория"><option value="">Все категории</option>${playerShop.categories.map(c=>`<option ${c===playerShopCategory?'selected':''}>${esc(c)}</option>`).join('')}</select><select id="player-shop-quality" aria-label="Качество"><option value="">Любое качество</option>${playerShop.qualities.map(c=>`<option ${c===playerShopQuality?'selected':''}>${esc(c)}</option>`).join('')}</select></div></header><div class="shop-layout"><section class="box"><h2>Купить</h2><div id="player-shop-items">${playerShop.items.map(i=>shopRow(i,false)).join('')||'<p>Товаров по этим фильтрам нет.</p>'}</div></section><section class="box"><h2>Продать</h2><p>Экипированные предметы сначала нужно снять. Лавка принимает предметы своего ассортимента.</p>${data.inventory.filter(i=>!i.equipped_slot&&(playerShop.saleOffers||[]).some(o=>o.id===i.id)&&(!playerShopCategory||i.category===playerShopCategory)&&(!playerShopQuality||i.quality===playerShopQuality)&&i.name.toLocaleLowerCase('ru').includes(playerShopQuery.toLocaleLowerCase('ru'))).map(i=>shopRow(i,true)).join('')||'<p>Нет подходящих предметов для продажи.</p>'}</section></div>`}
function shopRow(item,sell){const offer=(playerShop.saleOffers||[]).find(i=>i.id===item.id),price=sell?offer?.sell_price:item.buy_price,available=!!playerShop.settings.enabled&&(sell?!!offer:item.stock!==0);return `<article class="shop-item"><img data-quality="${esc(item.quality)}" src="${esc(item.image_url)}" alt="${esc(item.name)}" title="${esc(item.name)}${item.iconFallback?' · значок категории':''}"><div><button class="item-name" data-shop-inspect="${item.id}">${esc(item.name)}</button><p>${esc(item.category)} · ${esc(item.quality||'Обычное')} · ${price==null?'Не принимается':price+' медных'}</p><small>${sell?'У вас: '+item.quantity:'Запас: '+(item.stock===-1?'∞':item.stock)}</small></div><input aria-label="Количество" type="number" min="1" max="${Math.max(1,sell?Math.min(99,item.quantity):item.stock===-1?99:Math.min(99,item.stock))}" value="1"><button ${available?'':'disabled'} data-trade="${sell?'sell':'buy'}" data-trade-id="${sell?item.inventory_id:item.id}">${sell?'ПРОДАТЬ':'КУПИТЬ'}</button></article>`}
document.addEventListener('click',async e=>{const merchant=e.target.closest('[data-player-merchant]');if(merchant){playerShopKey=merchant.dataset.playerMerchant;playerShopCategory='';playerShopQuality='';playerShopQuery='';await loadPlayerShop();return}const button=e.target.closest('[data-trade]');if(button&&!button.disabled&&!shopPending){shopPending=true;button.disabled=true;try{const action=button.dataset.trade,body={action,shopKey:playerShopKey,quantity:+button.parentElement.querySelector('input').value};body[action==='buy'?'itemId':'inventoryId']=+button.dataset.tradeId;playerShop=await request(playerShopURL(),{method:'POST',body:JSON.stringify(body)});data=normalize(await request(`/api/portal/${encodeURIComponent(token)}`));renderCabinet();toast(playerShop.message)}catch(error){toast(error.message);button.disabled=false}finally{shopPending=false}}const inspect=e.target.closest('[data-shop-inspect]');if(inspect){const item=[...(playerShop?.items||[]),...data.inventory].find(i=>i.id===+inspect.dataset.shopInspect);if(item){$('#item-dialog-body').innerHTML=`<h2>${esc(item.name)}</h2><img data-quality="${esc(item.quality)}" src="${esc(item.image_url)}" alt="${esc(item.name)}"><p>${esc(item.category)} · ${esc(item.quality)} · ${item.value} медных</p><p>${esc(item.description)}</p><p>Урон: ${item.damage_min||0}–${item.damage_max||0} · Броня: ${item.armor||0} · Вес: ${item.weight||0}</p><h3>История</h3><p>${esc(item.lore||'')}</p>`;$('#item-dialog').showModal()}}});
document.addEventListener('change',e=>{if(e.target.id==='player-shop-category'){playerShopCategory=e.target.value;loadPlayerShop()}if(e.target.id==='player-shop-quality'){playerShopQuality=e.target.value;loadPlayerShop()}});
let shopTimer;document.addEventListener('input',e=>{if(e.target.id==='player-shop-search'){clearTimeout(shopTimer);playerShopQuery=e.target.value;shopTimer=setTimeout(()=>loadPlayerShop().then(()=>{const field=$('#player-shop-search');if(field&&tab==='shop'){field.focus();field.setSelectionRange(field.value.length,field.value.length)}}),450)}});
