let playerShop=null,shopPending=false;
function moneyText(w={}){return `${w.iron||0} железных · ${w.bronze||0} бронзовых · ${w.copper||0} медных колец`}
const originalPlayerRenderCabinet=renderCabinet;
renderCabinet=function(){originalPlayerRenderCabinet();$('#profile-head').insertAdjacentHTML('beforeend',`<div class="wallet-line">${moneyText(data.wallet)}<button data-tab="shop">МАГАЗИН</button></div>`)};
const originalPlayerRenderTab=renderTab;
renderTab=function(){if(tab==='shop'){renderPlayerShop();return}originalPlayerRenderTab()};
async function loadPlayerShop(q=''){try{playerShop=await request(`/api/portal/${encodeURIComponent(token)}/shop?q=${encodeURIComponent(q)}`);if(tab==='shop')renderPlayerShop()}catch(error){toast(error.message)}}
function renderPlayerShop(){const panel=$('#panel');if(!playerShop){panel.innerHTML='<section class="box"><h2>Открываем магазин…</h2></section>';loadPlayerShop();return}panel.innerHTML=`<header class="box"><h2>${esc(playerShop.settings.name)}</h2><div class="wallet-line">${moneyText(playerShop.wallet)}</div><p>100 медных = 1 бронзовое · 100 бронзовых = 1 железное. Цены ниже указаны в медных кольцах.</p>${playerShop.settings.enabled?'':'<p>Магазин закрыт мастером.</p>'}</header><div class="shop-layout"><section class="box"><h2>Купить</h2><input class="shop-search" id="player-shop-search" placeholder="Название или категория"><div id="player-shop-items">${playerShop.items.map(i=>shopRow(i,false)).join('')||'<p>Нет товаров. Мастер настраивает ассортимент.</p>'}</div></section><section class="box"><h2>Продать</h2><p>Экипированные предметы сначала нужно снять. Лавка принимает только предметы из своего ассортимента.</p>${data.inventory.filter(i=>!i.equipped_slot).map(i=>shopRow(i,true)).join('')||'<p>Нет предметов для продажи.</p>'}</section></div>`}
function shopRow(item,sell){const offer=(playerShop.saleOffers||playerShop.items).find(i=>i.id===item.id),price=sell?offer?.sell_price:item.buy_price,available=!!playerShop.settings.enabled&&(sell?!!offer:item.stock!==0);return `<article class="shop-item"><img src="${esc(item.image_url)}" alt=""><div><b data-shop-inspect="${item.id}">${esc(item.name)}</b><p>${esc(item.category)} · ${price==null?'Не принимается':price+' медных'}</p><small>${sell?'У вас: '+item.quantity:'Запас: '+(item.stock===-1?'∞':item.stock)}</small></div><input type="number" min="1" max="${sell?Math.min(99,item.quantity):item.stock===-1?99:Math.min(99,item.stock)}" value="1"><button ${available?'':'disabled'} data-trade="${sell?'sell':'buy'}" data-trade-id="${sell?item.inventory_id:item.id}">${sell?'ПРОДАТЬ':'КУПИТЬ'}</button></article>`}
document.addEventListener('click',async e=>{const button=e.target.closest('[data-trade]');if(button&&!button.disabled&&!shopPending){shopPending=true;button.disabled=true;try{const action=button.dataset.trade,body={action,quantity:+button.parentElement.querySelector('input').value};body[action==='buy'?'itemId':'inventoryId']=+button.dataset.tradeId;playerShop=await request(`/api/portal/${encodeURIComponent(token)}/shop`,{method:'POST',body:JSON.stringify(body)});data=normalize(await request(`/api/portal/${encodeURIComponent(token)}`));renderCabinet();toast(playerShop.message)}catch(error){toast(error.message);button.disabled=false}finally{shopPending=false}}const inspect=e.target.closest('[data-shop-inspect]');if(inspect){const item=[...(playerShop?.items||[]),...data.inventory].find(i=>i.id===+inspect.dataset.shopInspect);if(item){$('#item-dialog-body').innerHTML=`<h2>${esc(item.name)}</h2><img src="${esc(item.image_url)}" alt=""><p>${esc(item.description)}</p><h3>История</h3><p>${esc(item.lore)}</p>`;$('#item-dialog').showModal()}}});
let shopTimer;document.addEventListener('input',e=>{if(e.target.id==='player-shop-search'){clearTimeout(shopTimer);const q=e.target.value;shopTimer=setTimeout(async()=>{try{playerShop=await request(`/api/portal/${encodeURIComponent(token)}/shop?q=${encodeURIComponent(q)}`);const results=$('#player-shop-items');if(results)results.innerHTML=playerShop.items.map(i=>shopRow(i,false)).join('')}catch(error){toast(error.message)}},250)}});
